### ISSUE TITLE
Installation of apbs 3.0 binaries

### ISSUE THREAD

**Issue by poonmk** [Electrostatics/apbs#102]
Hello!

I would like to use the APBS 3.0 (Linux) binaries that I downloaded from SourceForge on a Ubuntu machine.  I can see the binary in the bin folder, but it appears to have dependencies on libraries in the other folders.  Seems to me that some kind of installation procedure is required, but I cannot find any documentation on how to do this, and it is not obvious to me how to do this on my own.  Many thanks in advance for your help.

Best wishes,
Gregory

**Comment by sobolevnrm** [comment]
Hi Gregory --

I'm sorry for the problems you're experiencing.  @intendo or @ashermancinelli -- can you please help with this?

Thanks

**Comment by ashermancinelli** [comment]
Could you try running from the lib dir or adding the lib dir to your `LD_LIBRARY_PATH`?

**Comment by poonmk** [comment]
> Could you try running from the lib dir or adding the lib dir to your `LD_LIBRARY_PATH`?

Thanks for the suggestion.  I tried that, and some other variations.  It keeps throwing this error:

../bin/apbs: error while loading shared libraries: libTABIPBlib.so: cannot open shared object file: No such file or directory

The referenced library is in the lib folder, and I added (exported) the lib folder to LD_LIBRARY_PATH, which I checked with $LD_LIBRARY_PATH.  Even when I tried running from the lib folder, I get the same error.

Thanks in advance for any other suggestions that you may have.

Best wishes,
Gregory

**Comment by intendo** [comment]
@poonmk can you post the output of `ldd apbs`? 
That will help show how the code was compiled and what it is missing.

**Comment by poonmk** [comment]
This is the output of `ldd apbs`:

	linux-vdso.so.1 (0x00007fff8be8e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f37d52a8000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f37d50c7000)
	libTABIPBlib.so => not found
	libmaloc.so.1 => /lib/libmaloc.so.1 (0x00007f37d4e6c000)
	libamd.so.1 => not found
	libpunc.so.1 => not found
	libmc.so.1 => not found
	libgamer.so.1 => not found
	libsuperlu.so.1 => not found
	libumfpack.so.1 => not found
	libblas.so.1 => not found
	libvf2c.so.1 => not found
	libtetgen.so.1 => not found
	libtriangle.so.1 => not found
	libreadline.so.7 => not found
	libtinfo.so.5 => not found
	libGeometricFlowLib.so => not found
	libPBAMLib.so => not found
	libPBSAMLib.so => not found
	libapbs_mg.so => not found
	libapbs_fem.so => not found
	libapbs_routines.so => not found
	libapbs_generic.so => not found
	libapbs_pmgc.so => not found
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f37d4e22000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f37d4dff000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f37d4c0d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f37d562d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f37d4bf2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f37d4bec000)

Hope this is helpful.

**Comment by Robinbrasil** [comment]
Okay, I actually dealt with something similar earlier today. First answer on Github, here I go.

Here is what `ldd $(which apbs)` returns me:

> 	linux-vdso.so.1 (0x00007fff93f57000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fca9adbf000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fca9aba5000)
> 	libTABIPBlib.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libTABIPBlib.so (0x00007fca9a991000)
> 	libmaloc.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libmaloc.so.1 (0x00007fca9a70d000)
> 	libamd.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libamd.so.1 (0x00007fca9a504000)
> 	libpunc.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libpunc.so.1 (0x00007fca9a302000)
> 	libmc.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libmc.so.1 (0x00007fca9a082000)
> 	libgamer.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libgamer.so.1 (0x00007fca99e5f000)
> 	libsuperlu.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libsuperlu.so.1 (0x00007fca99c0d000)
> 	libumfpack.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libumfpack.so.1 (0x00007fca9995d000)
> 	libblas.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libblas.so.1 (0x00007fca996ed000)
> 	libvf2c.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libvf2c.so.1 (0x00007fca994cf000)
> 	libtetgen.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libtetgen.so.1 (0x00007fca99248000)
> 	libtriangle.so.1 => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libtriangle.so.1 (0x00007fca99026000)
> 	libreadline.so.7 => /lib/x86_64-linux-gnu/libreadline.so.7 (0x00007fca98ddd000)
> 	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fca98daf000)
> 	libGeometricFlowLib.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libGeometricFlowLib.so (0x00007fca98b95000)
> 	libPBAMLib.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libPBAMLib.so (0x00007fca988dc000)
> 	libPBSAMLib.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libPBSAMLib.so (0x00007fca985be000)
> 	libapbs_mg.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libapbs_mg.so (0x00007fca98395000)
> 	libapbs_fem.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libapbs_fem.so (0x00007fca98182000)
> 	libapbs_routines.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libapbs_routines.so (0x00007fca97f67000)
> 	libapbs_generic.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libapbs_generic.so (0x00007fca97d33000)
> 	libapbs_pmgc.so => /archives/programas/apbs/APBS-3.0.0.Linux/lib/libapbs_pmgc.so (0x00007fca97af8000)
> 	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fca97ab1000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fca97a8e000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca9789c000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007fca9b153000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fca97881000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fca97879000)

As you can guess, "/archives/programas/apbs/APBS-3.0.0.Linux/lib" is the lib directory from apbs 3.0. I saw that most of your missing libraries (aside from libreadline.so.7 and libtinfo.so.5) were from apbs' lib directory, so I can only assume that the setting of the LD_LIBRARY_PATH wasn't quite right.

Could you perhaps use `echo $LD_LIBRARY_PATH` to check if it was set properly? And send the result and the path in which you extracted apbs here?

Now, for the two missing libraries that aren't from apbs. I actually dealt with a problem installing apbs earlier today where those exact libs were missing. I solved it by adding these libs in a directory and adding that directory to LD_LIBRARY_PATH as well (I couldn't add them on /lib/x86_64-linux-gnu for some reasons, but that may work if you try). 

tar.gz of the directory containing the libs (use `tar -xvzf extra_libs.tar.gz` to extract):
[extra_libs.tar.gz](https://github.com/Electrostatics/apbs/files/7610879/extra_libs.tar.gz)

Try adding that to the LD_LIBRARY_PATH in case you have problems with those 2 libs. Note that apbs seems to search for the names of the symbolic links that I put not the archives with the libs themselves, so, if you do anything (like pasting those libs on /lib/x86_64-linux-gnu) remember to move/recreate the symlinks with the names I put here too.

I hope this was useful.

**Comment by sobolevnrm** [comment]
Thank you!  @intendo and @nsoblath -- what do you think?

**Comment by intendo** [comment]
I am pretty sure this is taken care of with the changes that @nsoblath has been making. I don't think this will be an issue in the upcoming release.

**Comment by nsoblath** [comment]
The new release should solve these problems, I believe.  The automatic usage testing I'm putting together currently uses these steps to run APBS on an Ubuntu machine:

1. Install dependencies: `libsuitesparse-dev`, `libsuperlu-dev`, and `libopenblas-dev` installed with `apt`
2. Download the zip file with the pre-built binaries
3. Unzip and run

Step 3 could be done like this:
```
> unzip APBS*.zip
> APBS_DIR=[directory produced by the unzip command]
> export PATH=${APBS_DIR}/bin:$PATH
> cd ${APBS_DIR}/share/apbs/examples/born
> apbs apbs-apolar.in
```
