### ISSUE TITLE
Tests fail if setup command cannot be found

### ISSUE THREAD

**Issue by intendo** [Electrostatics/apbs#108]
**Describe the bug**
The tests can have a "setup" section that runs a command before running the test. The problem is that if the command does not exist, the test fails.

**To Reproduce**
Install python3 on Ubuntu (no python installed by default)

**Expected behavior**
The "setup" for test, protein-rna, should call the python (the same one running the test) instead of hardcoding python.

This could be handled a few ways:
1. If the setup command starts with "^python\s+" then it can be substituted for sys.executable.
2. A keyword like __PYTHON__ could be used in the setup and then substituted with sys.executable

@sobolevnrm I am leaning towards option number 1 unless you have any other suggestion.

**Comment by sobolevnrm** [comment]
@intendo can you please post a link to the offending code?

**Comment by intendo** [comment]
The code is at lines 186-188 in tests/apbs_tester.py:
```
    # Run the setup, if any
    if setup:
        subprocess.call(setup.split())
```
The value of setup comes from the test_cases.cfg, line 112, such as the one for protein-rna, where a precondition is to run `python apbs_dx.py` to create all the data files.

The code in apbs_tester.py should be changed to something like the following if the first value start with python:
```
        subprocess.call([sys.executable, setup.Skip(1).ToArray())
```

That way the sys.executable will work if it is python, python3, python37, python.exe, etc.
