### ISSUE TITLE
Bad Xcode value in Cmake

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs#109]
The file `build/CMakeCache.txt` sets `CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk`; however, my Mac (10.15.7) has the directories `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk` and `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` instead.  The former is a symbolic link to the latter, making me think that the `build/CMakeCache.txt` entry should be `CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` instead.

**Comment by ashermancinelli** [comment]
Did the above comment resolve this or are you still experiencing this?

**Comment by sobolevnrm** [comment]
I can build the basic APBS binary with this new option.  Can you please update the documentation accordingly?
