### ISSUE TITLE
Parsing PQR files does not flag errors in file

### ISSUE THREAD

**Issue by intendo** [Electrostatics/apbs#119]
When parsing *.pqr files, an error in the file is skipped (e.g. ATAM vs ATOM).

The code should warn the user that there is an error in the file.

**Comment by sobolevnrm** [comment]
I'd like to replace the PQR-parsing code with Python and have PDB2PQR import it to reduce code duplication.

**Comment by intendo** [comment]
@sobolevnrm I agree. We just updated the PQR parsing code to be able to parse all the pqr files in the examples directory. We made the grammar be able to handle blank lines, REMARKS, TER, and END lines.
