### ISSUE TITLE
Update libreadline dependency to allow for libreadline8?

### ISSUE THREAD

**Issue by chelsell** [Electrostatics/apbs#130]
Hi there,

I was trying to use the precompiled binaries on my Ubuntu 20.04.1 LTS system, but got errors related to libreadline.so.7. 20.04 progressed to libreadline.so.8. I couldn't seem to find 20.04-compatible versions of libreadline.so.7. I ended up making libreadline.so.7 a symbolic link to libreadline.so.8, and so far that appears to work just fine. I don't know much about managing library dependencies, but maybe you can either allow for libreadline.so.8 or add libreadline.so.7 to the libraries you provide in the package?

Best,
Cole

**Comment by sobolevnrm** [comment]
Hi Cole --

Thank you for the feedback.  We would love to get a PR with your fix.

Thanks!

**Comment by intendo** [comment]
Thanks @chelsell , we are trying to update our compiled version to use Ubuntu 20.04 and it will probably use libreadline.so.8.
There are lots of library dependencies and we are trying to get them updated with a more modern version of CMake for the build system. Hopefully the symbolic link will work for you. If not, let us know and we will keep trying to get a better build of APBS and make it available.

**Comment by intendo** [comment]
I am sure that since we are using Ubuntu 20.04 in the Github Actions build that this has been resolved.
