### ISSUE TITLE
Similarity Tool

### ISSUE THREAD

**Issue by sbembenek18** [Electrostatics/apbs#132]
I attempted to use the tool 'similarity'. I provided it with two DX files made via the APBS Pymol plugin. The files were successfully read by the program however, when it came time to actually calculate the similarity, I incurred a 'segmentation fault'

**Comment by sobolevnrm** [comment]
Thank you; this is a known bug but we haven't documented it yet.

**Comment by sbembenek18** [comment]
thanks -- so the Similarity Tool does not current work then?

best,

Scott

Scott Bembenek, Founder, CEO, CSO
Denovicon Therapeutics <https://www.denovicontx.com/>
1130 Wall St #558
La Jolla, CA 92037
<https://www.denovicontx.com/>

**Comment by sobolevnrm** [comment]
Correct.  It should be straightforward to reimplement in Python and is in my queue of to-do items.  Any help is welcome!  Thanks.

**Comment by sbembenek18** [comment]
OK, we'll take a look at our end as well then. Is there currently a
non-Python working version?

Scott Bembenek, Founder, CEO, CSO
Denovicon Therapeutics <https://www.denovicontx.com/>
1130 Wall St #558
La Jolla, CA 92037
<https://www.denovicontx.com/>

**Comment by sobolevnrm** [comment]
@intendo Do you know if we have a historical working version of this?

**Comment by intendo** [comment]
No, it does not look like we have been building the binaries in the tools directory since before I joined the project. I checked and the tools are not being built in APBS 1.5. There is CMake support for building them and I updated and tested it on the main branch. The newest build, https://github.com/Electrostatics/apbs/actions/runs/665807719, for Mac and Ubuntu. I downloaded the APBS-3.1.3.Darwin build and it has the share/apbs/tools/bin/similarity binary built from https://github.com/Electrostatics/apbs/blob/master/tools/mesh/similarity.c

**Comment by sobolevnrm** [comment]
Thanks, @intendo.  @sbembenek18 does this work for you?

**Comment by sbembenek18** [comment]
Hey,

I'm using the binary install for APBS-3.0.0 (under Centos 7), FYI.

Under Apps/APBS-3.0.0/share/apbs/tools/bin 'similarity' is compiled and it
does seem to work in general. The segmentation fault occurred for a
particular (small) molecule, but it does not occur for the several
molecules (68) we have looked at so far; I'll need to investigate further
to better understand the issue with that one molecule.

Thanks again for your help.

Scott

Scott Bembenek, Founder, CEO, CSO
Denovicon Therapeutics <https://www.denovicontx.com/>
1130 Wall St #558
La Jolla, CA 92037
<https://www.denovicontx.com/>

**Comment by sobolevnrm** [comment]
Great! I just created a separate issue for reimplementing in Python (although its a subset of something else I'm supposed to be working on) and will close this issue for now since you have a working solution.

**Comment by sbembenek18** [comment]
Thanks

**Comment by sbembenek18** [comment]
Quick follow up on 'similarity' ...

I do note that a segmentation fault occurs with 'similarity' when going
from a grid size of 65 to 97  -- for a size of 33, it works (aside from the
problem molecule I mentioned before & that I am still confirming).

**Comment by sbembenek18** [comment]
Rather, for a size of 33 and 65 it works.

Scott Bembenek, Founder, CEO, CSO
Denovicon Therapeutics <https://www.denovicontx.com/>
1130 Wall St #558
La Jolla, CA 92037
<https://www.denovicontx.com/>
