### ISSUE TITLE
ERROR WHILE COMPILING

### ISSUE THREAD

**Issue by biswasakash95** [Electrostatics/apbs#145]
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp: In function ‘void bind_valist(pybind11::module&)’:
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp:79:30: error: ‘Valist_getAtomList’ was not declared in this scope
   79 |     .def("getAtomList"    , &Valist_getAtomList)
      |                              ^~~~~~~~~~~~~~~~~~
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp:80:30: error: ‘Valist_getCenterX’ was not declared in this scope
   80 |     .def("getCenterX"     , &Valist_getCenterX)
      |                              ^~~~~~~~~~~~~~~~~
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp:81:30: error: ‘Valist_getCenterY’ was not declared in this scope
   81 |     .def("getCenterY"     , &Valist_getCenterY)
      |                              ^~~~~~~~~~~~~~~~~
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp:82:30: error: ‘Valist_getCenterZ’ was not declared in this scope
   82 |     .def("getCenterZ"     , &Valist_getCenterZ)
      |                              ^~~~~~~~~~~~~~~~~
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp:83:30: error: ‘Valist_getNumberAtoms’ was not declared in this scope
   83 |     .def("getNumberAtoms" , &Valist_getNumberAtoms)
      |                              ^~~~~~~~~~~~~~~~~~~~~
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp:84:30: error: ‘Valist_getAtom’ was not declared in this scope
   84 |     .def("getAtom"        , &Valist_getAtom)
      |                              ^~~~~~~~~~~~~~
/home/akash/APBS/apbs/tools/python-pybind/bind_valist.cpp:85:30: error: ‘Valist_memChk’ was not declared in this scope
   85 |     .def("memChk"         , &Valist_memChk)
      |                              ^~~~~~~~~~~~~
make[2]: *** [tools/python-pybind/CMakeFiles/apbs_pybind.dir/build.make:121: tools/python-pybind/CMakeFiles/apbs_pybind.dir/bind_valist.cpp.o] Error 1
make[2]: Leaving directory '/home/akash/APBS/apbs/build'
make[1]: *** [CMakeFiles/Makefile2:1296: tools/python-pybind/CMakeFiles/apbs_pybind.dir/all] Error 2
make[1]: Leaving directory '/home/akash/APBS/apbs/build'
make: *** [Makefile:169: all] Error 2

**Comment by sobolevnrm** [comment]
@intendo do you have thoughts on how to fix this?  Thanks!

**Comment by intendo** [comment]
I would need to know more information like:
- OS and version (e.g., Linux Ubuntu 18.04)
- Compiler and version (e.g., g++-9)
- Python  version (e.g., 3.6.7)
- The steps used to produce the output.

**Comment by intendo** [comment]
Thanks Akash, can you tell me what version of Linux? 
Is it Centos or Ubuntu or Mint?
What version of Linux (e.g. `cat /etc/os-release`)
Did you get the source code from [Release 3.0.0](https://github.com/Electrostatics/apbs/releases/tag/v3.0.0) or the latest version?
The problem looks like Pybind11 is not finding files.
If you don't need the Python interface, I would recommend using the `-DENABLE_PYTHON=OFF`.

**Comment by biswasakash95** [comment]
Hello Darren,

I took the source code from the site you mentioned.
The version of Ubuntu Ubuntu 20.04.2 LTS
I will try with the -DENABLE_PYTHON=OFF

If I download the Linux version how do I install it. Because in the Linux
version of the code there are only four folders
bin, include, lib and share and there is no installation guide present in
the folder. I am sorry if I am asking too much.

Regards
Akash

**Comment by biswasakash95** [comment]
Hello Darren,

These are the steps that I am using:

1. git clone https://github.com/Electrostatics/apbs
2. cd apbs/
3. git submodule init
4. git submodule update
5. mkdir build
6. cd build
7. export APBS_BUILD_DIR=`echo $(pwd)`
8. export INSTALL_DIR=$HOME/apbs
9. export PATH=$INSTALL_DIR/bin:$PATH
10. cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DENABLE_PYTHON=OFF
-DBUILD_SHARED_LIBS=ON -DENABLE_GEOFLOW=ON -DENABLE_BEM=ON -DENABLE_FETK=ON
-DENABLE_PBAM=ON -DENABLE_PBSAM=ON ..
11. VERBOSE=1 make -j 1
12. cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DENABLE_PYTHON=OFF
-DBUILD_SHARED_LIBS=ON -DENABLE_GEOFLOW=ON -DENABLE_BEM=ON -DENABLE_FETK=ON
-DENABLE_PBAM=ON -DENABLE_PBSAM=ON ..
13. VERBOSE=1 make -j 1 install

I followed the above and it worked.

Thanks with Regards
Akash

**Comment by intendo** [comment]
Great, thanks Akash for sharing how you got it to work. I am going to close this issue.

**Comment by BJWiley233** [comment]
I am having this same issue with exact same functions with AppleClang 13.  It is happening I think because in valist.h [VINLINE_VATOM](https://github.com/Electrostatics/apbs/blob/master/src/generic/valist.h#L97) is defined [here](https://github.com/Electrostatics/apbs/blob/bcd52c6d3646e0c372c657f38af5a656b7c3d158/src/generic/vhal.h#L476) and the only reason I can see this is in Visual Studio, shows me 2 things:
1. Hovering over `&Valist_getAtomList` indicates `(<error-type>) <error> > (error) ((const char[5])"vmem", &sValist::vmem)` and I don't get this when hovering over 
2. when I click on a definition in bind_valist.cpp, for example on &Valist_getAtomList I get taken to the valist header [here](https://github.com/Electrostatics/apbs/blob/bcd52c6d3646e0c372c657f38af5a656b7c3d158/src/generic/valist.h#L105) and it's not compiled because `VINLINE_VATOM` is defined.  But when I click on a function that is actually declared such as &Valist_readPQR I get taken to valist.c where the function is declared.

Here is the output:
```
[ 95%] Building CXX object tools/python-pybind/CMakeFiles/apbs_pybind.dir/bind_valist.cpp.o
+ cd /Users/brian/tools/test/apbs/build2/tools/python-pybind
+ /usr/bin/g++ -DENABLE_GEOFLOW -DENABLE_PBAM -DENABLE_PBSAM -DENABLE_PYGBE -DPBAM_APBS -DPBSAM_APBS -D__LAU -D__MACOS -Dapbs_pybind_EXPORTS -I/Users/brian/tools/test/apbs/build2/_deps/fetk-src/include -I/Users/brian/tools/test/apbs/build2/_deps/geoflow-src/src -I/usr/local/include/eigen3 -I/Users/brian/tools/test/apbs/externals/pb_s_am/pbam/src -I/Users/brian/tools/test/apbs/externals/pb_s_am/pb_shared/src -I/Users/brian/tools/test/apbs/externals/pb_s_am/pb_wrap/src -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers -I/Users/brian/tools/test/apbs/externals/pb_s_am/pbsam/src -I/Users/brian/tools/test/apbs/src -I/Users/brian/tools/test/apbs/build2/src -I/Users/brian/tools/test/apbs/include -isystem /opt/intel/oneapi/intelpython/latest/include/python3.9 -isystem /opt/intel/oneapi/intelpython/latest/include -I/usr/local/Cellar/libomp/13.0.0/include -L/usr/local/Cellar/libomp/13.0.0/lib -lomp -I/Users/brian/tools/apbs/src -I/usr/local/Cellar/superlu/5.2.2_1/include -L/usr/local/Cellar/superlu/5.2.2_1/lib -Wall -Wpedantic -fpermissive -fPIC -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX-SDKs/MacOSX11.3.sdk -mmacosx-version-min=11.3 -fPIC -std=gnu++17 -MD -MT tools/python-pybind/CMakeFiles/apbs_pybind.dir/bind_valist.cpp.o -MF CMakeFiles/apbs_pybind.dir/bind_valist.cpp.o.d -o CMakeFiles/apbs_pybind.dir/bind_valist.cpp.o -c /Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp
clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/Cellar/libomp/13.0.0/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/Cellar/superlu/5.2.2_1/lib' [-Wunused-command-line-argument]
/Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp:82:30: error: use of undeclared identifier 'Valist_getAtomList'
    .def("getAtomList"    , &Valist_getAtomList)
                             ^
/Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp:83:30: error: use of undeclared identifier 'Valist_getCenterX'
    .def("getCenterX"     , &Valist_getCenterX)
                             ^
/Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp:84:30: error: use of undeclared identifier 'Valist_getCenterY'
    .def("getCenterY"     , &Valist_getCenterY)
                             ^
/Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp:85:30: error: use of undeclared identifier 'Valist_getCenterZ'
    .def("getCenterZ"     , &Valist_getCenterZ)
                             ^
/Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp:86:30: error: use of undeclared identifier 'Valist_getNumberAtoms'
    .def("getNumberAtoms" , &Valist_getNumberAtoms)
                             ^
/Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp:87:30: error: use of undeclared identifier 'Valist_getAtom'
    .def("getAtom"        , &Valist_getAtom)
                             ^
/Users/brian/tools/test/apbs/tools/python-pybind/bind_valist.cpp:88:30: error: use of undeclared identifier 'Valist_memChk'
    .def("memChk"         , &Valist_memChk)
                             ^
7 errors generated.
make[2]: *** [tools/python-pybind/CMakeFiles/apbs_pybind.dir/bind_valist.cpp.o] Error 1
make[1]: *** [tools/python-pybind/CMakeFiles/apbs_pybind.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by intendo** [comment]
@BJWiley233 the Python code for APBS is still very new and needs significant effort before you will be able to call APBS and solvers from Python. Eventually the plan is to make APBS be written mostly in Python and then you would install it with pip install apbs.

**Comment by BJWiley233** [comment]
@intendo thanks for the update/warning so I don't have to spend any more time.  I didn't get it to compile the bindings however.  It seems that may pybind11 module in general might not be able to see the `inline` well with the compiler(s) in general.  Despite Nathan's  2010 inline code and Todd's  2005's python/swig code, the machinery/compiles had been tinkered a bit.
