### ISSUE TITLE
Problem while calculating protein-protein electrostatic energy

### ISSUE THREAD

**Issue by srdjan125** [Electrostatics/apbs#147]
Hello,

I want to calculate electrostatic energy between two proteins while their distance is varied, ie initial center-to-center distance when two proteins are in close contact is around 3nm, and final distance when two proteins are far away from each other is 30nm. 
 I want to calculate their electrostatic interaction energy as a function of their distance (Coloumb energy substracted by solvation energy due to ionic solvent screening).

  This this, I have tried binding energy calculations like in this tutorial: https://www.ics.uci.edu/~dock/manuals/apbs/html/tutorial/x307.html where I calculate energy of A, energy of B, energy of AB complex and then Interaction_energy=AB-A-B.

  I have used the same parameters like in the above link except the dime, cglen and fglen which I have determined by pysize.py python program.
   For the case when proteins are far away the parameters are:
    mg-auto
    dime 129 129 801
    cglen 62.353 70.198 647.884
    fglen 56.678 61.293 401.108

For the case when proteins are in closest contact parameters given by pysize.py are:
   mg-auto
    dime 97 129 129
    cglen 62.353 70.195 139.584
    fglen 56.678 61.291 102.108

I have understood that I should use the same grid parameters for all calculations, so I have used the first parameters for both calculations.

   However, I got some illogical result: electrostatic energy between A and B is higher when they are 30nm away then when they are 3nm away, which is counterintuitive: there should be higher repulsion energy between two proteins in close contact then in case when they are far away.

  I have tried to do the same calculations after putting salt concentration is 0, and in that case I got "correct" results: there is high electrostatic repulsive energy in close contact and low one at 30nm distance.
  From this I understand that there might be issue from electrostatic energy of salts around proteins, so this term does not cancel out. I also think it might be the problem of centering fine grid: in one case fine grid is centered on short distance AB complex, while in another case in the middle of two proteins (at 15nm distance between them), but if I place fine grid on protein A, then protein B will be 30nm away and not part of fine grid.

I can get "correct" ratio of energies when I take these parameters:
    mg-auto
    dime 129 129 801
    cglen 129 129 801
    fglen 56.678 61.293 401.108
however this size of cglen is not recommended by APBS tutorial or pysize.py program. I am new to APBS, but in case of MD it would make sense to take larger box size to cancel out local solvent effects. 

   I would appreciate if someone could help me with this issue or give some advice what might be the problem.
   Should I do calculations for full thermodynamics cycle? 
   Or instead of using lpbe I should use lrpbe to get solvation energies directly and calculate Coloumb energies separately?

**Comment by sobolevnrm** [comment]
This seems more appropriate for a discussion than an issue.  I'm closing this and will respond to #146.
