### ISSUE TITLE
Cannot build APBS source following RTD instructions

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs#177]
**Describe the bug**

`bash .build.sh` does not work on Ubuntu 20.04.3 (WSL).

**To Reproduce**

1. `git pull` on master
2. `bash .build.sh`
3. See error:

```bash
~/Documents/Git/apbs$ bash .build.sh
.build.sh: line 2: $'\r': command not found
==================================== WHICH GCC ====================================
.build.sh: line 8: syntax error near unexpected token `$'in\r''
'build.sh: line 8: `case "${ostype}" in
```

**Expected behavior**

[Our documentation](https://apbs.readthedocs.io/en/latest/getting/source.html#get-source-directly-from-github) claimed this would work! :)

**Comment by intendo** [comment]
This is problem with WSL and bash scripts in general. I am assuming that you are using WSLv2.

You will probably need to run `dos2unix .build.sh` or the following to resolve the newline issue:
```
tr -d "\r" < .build.sh > a.tmp
mv a.tmp .build.sh
```

Also, I don't know what `uname -s` returns on WSL so you may have modify line 12 or 13 to be the output of `uname -s`; or just add the following on line 2:
`export CC=gcc-9; export CXX=g++-9`

**Comment by sobolevnrm** [comment]
D'oh.
