### ISSUE TITLE
Dx file not produced on webserver

### ISSUE THREAD

**Issue by mmaldo520** [Electrostatics/apbs#178]
Hello,
I have not been able to get a .dx output using the pdb2pqr and apbs webservers for a particular molecule. I thought it might be an issue with the ligands, so I deleted them and re-submitted, but I am still unable to get a .dx file. (I can get the .dx starting with other pdbs.) The most recent job IDs are: kh8ryc5dcl and f6czyesay6.

Could you help me figure this out?

Thank you

**Comment by intendo** [comment]
The jobs exit with and exit status of -9 which typically means that the process runs out of memory. The generated PQR file is 12MB so it is probably exceeding the amount of memory available on our images (current limit is 16 Gbytes of memory).

Can you run these on your local computer?

**Comment by sobolevnrm** [comment]
I'm going to close this since @mmaldo520 hasn't responded.
