### ISSUE TITLE
negative potentials on atoms of positively charged residues

### ISSUE THREAD

**Issue by deekshatcb** [Electrostatics/apbs#180]
I want to calculate potential on specific atoms of some residues in a protein. From the .dx file (using the interpolate function) I was extracting the potentials on the grid points nearest to the atoms of interest, some of which happens to be NZ atoms of lysine. I am getting negative potentials. Is it normal? or am I doing something wrong?

**Comment by sobolevnrm** [comment]
Can you please say more about how you're performing the calculation?  Is this for a single calculation or for the difference of two calculations (e.g., for solvation energy and reaction potential)?

Note that you can get the value of the potential at an atom center using [write atompot](https://apbs.readthedocs.io/en/latest/using/input/old/elec/write.html).
