### ISSUE TITLE
Missing iapbs library in APBS binary

### ISSUE THREAD

**Issue by intendo** [Electrostatics/apbs#187]
**Describe the bug**
User's have sent email describing that the get an error message of missing the libiapbs.so library.
@nsoblath can you verify that the iapbs.a is linked in with the apbs binary?

**Comment by nsoblath** [comment]
@intendo The default configuration when building APBS is to have iAPBS disabled, and I haven't tried using it.  I don't know what version the users who see this bug are using, but at least for future releases I can look at including IAPBS.

**Comment by nsoblath** [comment]
Starting with c9b61f9558da240212cadf6078218f367f8f47e2 (currently on branch `nsoblath/issue_163`) I've made the build include iAPBS by default, and have checked that the library `libiapbs.a` is in fact linked into the `apbs` executable.

This improvement will be built into the new release of APBS once #163 is complete, and this matter is now covered by that issue.  Thanks!
