### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by aaomoniyi** [Electrostatics/apbs#195]
Dear All,

Compliments of the season!
I tried to compile APBS from the source code and the get the error below. Please I need your help, I know something went wrong but I could not figure it out. I'm a beginer.

cmake -DCMAKE_INSTALL_PREFIX=/opt/apbs -DENABLE_BEM=OFF -DENABLE_iAPBS=ON -DENABLE_PBAM=ON ..

CMake Deprecation Warning at CMakeLists.txt:43 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- #############################################################
-- ** PROJECT NAME:  APBS
-- ** PROJECT DESC:  Adaptive Poisson-Boltzmann Solver
-- ** PROJECT URL:   http://www.poissonboltzmann.org/
-- ** VERSION_DATA:  3.2.1
-- ** CURRENT_TIME:  2022-01-01T03:48:56
-- ** CURRENT_YEAR:  2022
-- Setting project paths
-- Setting lookup paths for headers and libraries
-- Computing machine epsilon values
-- Floating point epsilon is 2.220446e-16
-- Double precision epsilon is 2.220446e-16
-- Looking for time
-- Looking for time - found
-- Looking for rand
-- Looking for rand - found
-- Looking for srand
-- Looking for srand - found
Configuring build for MALOC
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of mode_t
-- Check size of mode_t - done
-- Check size of pid_t
-- Check size of pid_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/un.h
-- Looking for include file sys/un.h - found
-- Looking for include file sys/wait.h
-- Looking for include file sys/wait.h - found
-- Looking for include file netinet/in.h
-- Looking for include file netinet/in.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Looking for include file netdb.h
-- Looking for include file netdb.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file rpc/rpc.h
-- Looking for include file rpc/rpc.h - found
-- Looking for getcwd
-- Looking for getcwd - found
-- Looking for O_NONBLOCK
-- Looking for O_NONBLOCK - found
-- Type: INTERNAL_HEADERS
-- Items: /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/build/externals/fetk/maloc/src/maloccf.h
-- Type: SOURCES
-- Items: maloc_base.c
-- Type: EXTERNAL_HEADERS
-- Items: maloc/maloc.h;maloc/maloc_base.h
-- Type: INTERNAL_HEADERS
-- Items: maloc_base_p.h
-- Type: SOURCES
-- Items: psh.c;vcom.c;vmp.c;vmpi.c
-- Type: EXTERNAL_HEADERS
-- Items: maloc/psh.h;maloc/vcom.h;maloc/vmp.h;maloc/vmpi.h
-- Type: INTERNAL_HEADERS
-- Items: psh_p.h;vcom_p.h;vmpi_p.h;vmp_p.h
-- Type: SOURCES
-- Items: vlex.c;vpars.c;vpup.c;vsh.c;vyacc.c
-- Type: EXTERNAL_HEADERS
-- Items: maloc/vsh.h
-- Type: INTERNAL_HEADERS
-- Items: vpup.h;vsh_p.h;vyacc.h
-- Type: SOURCES
-- Items: vio.c;viofb.c;vmem.c;vnm.c;vnmfb.c;vpred.c;vset.c;ziofb.c
-- Type: EXTERNAL_HEADERS
-- Items: maloc/vio.h;maloc/vmem.h;maloc/vnm.h;maloc/vset.h;maloc/vsys.h;maloc/vpred.h
-- Type: INTERNAL_HEADERS
-- Items: vio_p.h;vmem_p.h;vnm_p.h;vpred_p.h;vset_p.h
CMake Error at externals/fetk/maloc/src/CMakeLists.txt:40 (install):
  install FILES given no DESTINATION!

-- Building PBAM
-- Inline functions enabled
-- Verbose debugging mode enabled
-- Adding apbs_generic
-- With source files nosh.c;mgparm.c;femparm.c;pbamparm.c;pbsamparm.c;pbeparm.c;bemparm.c;geoflowparm.c;apolparm.c;vacc.c;valist.c;vatom.c;vpbe.c;vcap.c;vclist.c;vstring.c;vparam.c;vgreen.c
-- With external header files nosh.h;mgparm.h;femparm.h;pbamparm.h;pbsamparm.h;pbeparm.h;bemparm.h;geoflowparm.h;apolparm.h;vacc.h;valist.h;vatom.h;vpbe.h;vcap.h;vclist.h;vstring.h;vparam.h;vgreen.h;vmatrix.h;vhal.h;vunit.h
-- With internal header files 
-- With library dependencies m;stdc++;maloc;PBAMLib
-- Added apbs_generic
-- Adding apbs_pmgc
-- With source files buildAd.c;buildBd.c;buildGd.c;buildPd.c;cgd.c;gsd.c;matvecd.c;mgcsd.c;mgdrvd.c;mgsubd.c;mikpckd.c;mlinpckd.c;mypdec.c;newtond.c;newdrvd.c;powerd.c;smoothd.c;mgfasd.c
-- With external header files buildAd.h;buildBd.h;buildGd.h;buildPd.h;cgd.h;gsd.h;matvecd.h;mgcsd.h;mgdrvd.h;mgsubd.h;mikpckd.h;mlinpckd.h;mypdec.h;newtond.h;newdrvd.h;powerd.h;smoothd.h;mgfasd.h
-- With internal header files 
-- With library dependencies m;stdc++;maloc;PBAMLib
-- Added apbs_pmgc
-- Adding apbs_mg
-- With source files vgrid.c;vmgrid.c;vopot.c;vpmg.c;vpmgp.c
-- With external header files vgrid.h;vmgrid.h;vopot.h;vpmg.h;vpmgp.h
-- With internal header files 
-- With library dependencies m;stdc++;maloc;PBAMLib;apbs_generic;apbs_pmgc
-- Added apbs_mg
-- Adding apbs_routines
-- With source files routines.c
-- With external header files 
-- With internal header files 
-- With library dependencies m;stdc++;maloc;PBAMLib
-- Added apbs_routines
-- External Headers: 
--  
-- APBS Libraries: m;stdc++;maloc;PBAMLib
-- Internal Libraries: apbs_generic;apbs_pmgc;apbs_mg;apbs_routines
--  
--  -fPIC
-- Building documentation enabled
-- ================================================================
-- ================================================================
-- Supplemental tools enabled
-- Building mesh
-- libraries: apbs_generic;apbs_mg;apbs_pmgc
-- Building manip
-- libraries: apbs_generic;apbs_mg;apbs_pmgc
-- Building of iAPBS interface enabled
-- ******* TESTING ADDED *****************
-- Found Python3: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter 
-- ******* Python3 FOUND /usr/bin/python3.8
-- ******* FOUND TEST CASE born, born
-- TEST  born_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t born
-- ******* FOUND TEST CASE actin, actin-dimer-auto
-- TEST  actin-dimer-auto_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t actin-dimer-auto
-- ******* FOUND TEST CASE actin, actin-dimer-parallel
-- TEST  actin-dimer-parallel_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t actin-dimer-parallel
-- ******* FOUND TEST CASE alkanes, alkanes
-- TEST  alkanes_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t alkanes
-- ******* FOUND TEST CASE FKBP, FKBP
-- TEST  FKBP_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t FKBP
-- ******* FOUND TEST CASE hca, hca-bind
-- TEST  hca-bind_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t hca-bind
-- ******* FOUND TEST CASE ionize, ionize
-- TEST  ionize_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t ionize
-- ******* FOUND TEST CASE ion, ion-pmf
-- TEST  ion-pmf_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t ion-pmf
-- ******* FOUND TEST CASE ion, ion-protein
-- TEST  ion-protein_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t ion-protein
-- ******* FOUND TEST CASE pka, pka-lig
-- TEST  pka-lig_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t pka-lig
-- ******* FOUND TEST CASE point, point-pmf
-- TEST  point-pmf_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t point-pmf
-- ******* FOUND TEST CASE solv, solv
-- TEST  solv_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t solv
-- ******* FOUND TEST CASE geoflow, geoflow
-- ******* SKIPPING TEST CASE geoflow, geoflow
-- ******* FOUND TEST CASE bem, bem
-- ******* SKIPPING TEST CASE bem, bem
-- ******* FOUND TEST CASE bem, bem-pKa
-- ******* SKIPPING TEST CASE bem, bem-pKa
-- ******* FOUND TEST CASE bem, bem-binding-energy
-- ******* SKIPPING TEST CASE bem, bem-binding-energy
-- ******* FOUND TEST CASE pbam, pbam
-- TEST  pbam_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t pbam
-- ******* FOUND TEST CASE pbsam, pbsam
-- ******* SKIPPING TEST CASE pbsam, pbsam
-- ******* FOUND TEST CASE protein, protein-rna
-- TEST  protein-rna_test  WORKING_DIRECTORY  /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests  COMMAND /usr/bin/python3.8 /home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/tests/apbs_tester.py -e apbs -t protein-rna
-- Configuring incomplete, errors occurred!
See also "/home/akinyemi/Downloads/APBS-3.0.0_Source-Code(1)/apbs-3.0.0/apbs/apbs/build/CMakeFiles/CMakeOutput.log".

**Comment by BJWiley233** [comment]
Can you paste your entire `cmake -DCMAKE_INSTALL_PREFIX=/opt/apbs -DENABLE_BEM=OFF -DENABLE_iAPBS=ON -DENABLE_PBAM=ON ..` after the `..` ?  Did you add `-DENABLE_PYTHON`?  Also which operating system are you using?  Try making the prefix /usr/local/apbs.  This shouldn't make a difference.

**Comment by BJWiley233** [comment]
You can also try install a conda installation of python as it will be easier to use APBS, PDB2PQR, and psi4 (if you intend to use that package in your work)

**Comment by intendo** [comment]
@aaomoniyi sorry for the confusion. This repo uses CMake to build APBS and all the components. You can look at the Github Actions file, https://github.com/Electrostatics/apbs/blob/master/.github/workflows/build.yml, to see how you can build APBS using CMake on Windows, Mac, and Linux.

**Comment by nsoblath** [comment]
I think there is probably an unfortunate bug in how FETK was built by APBS on the master branch (as of this writing, at least, at commit 34fd2bbacb84e1289490fe746ba0cc7553a23ce2).  This has been fixed in the version being prepared for release shortly.

**Comment by aaomoniyi** [comment]
> Can you paste your entire `cmake -DCMAKE_INSTALL_PREFIX=/opt/apbs -DENABLE_BEM=OFF -DENABLE_iAPBS=ON -DENABLE_PBAM=ON ..` after the `..` ? Did you add `-DENABLE_PYTHON`? Also which operating system are you using? Try making the prefix /usr/local/apbs. This shouldn't make a difference.

I did not add this -DENABLE_PYTHON. The operating system is ubuntu 20.04. The entire code I used was cmake -DCMAKE_INSTALL_PREFIX=/opt/apbs -DENABLE_BEM=OFF -DENABLE_iAPBS=ON -DENABLE_PBAM=ON ..

**Comment by BJWiley233** [comment]
OMG so silly I thought `..` meant rest of command and not the parent directory.  WOW.  Try with `-DENABLE_PYTHON`

**Comment by Drvanon** [comment]
@nsoblath, I am having the issue with FETK as well. Has your fix been released yet?

**Comment by nsoblath** [comment]
@Drvanon [v3.4.0](https://github.com/Electrostatics/apbs/releases/tag/v3.4.0) was released a couple weeks ago, and it shouldn't have this problem.  I'll close this issue now, and if you run into any other difficulties, please open a new issue.
