### ISSUE TITLE
Independence of results to cation radius

### ISSUE THREAD

**Issue by mfornace** [Electrostatics/apbs#200]
Hi, thanks for the great software first of all. We were running some calculations on RNA molecules with Na and K in solution (with Cl anions). We noticed that swapping Na for K (which just changes the ion radius) did not affect our electrostatic energies measured in APBS. 

I diagnosed this to be the result of the behavior mentioned in the documentation that "only the largest ionic radius is used to determine the ion-accessibility function". Cl is larger than Na and K, so there does not seem to be any way to distinguish them in the calculations. Do you have a suggestion for how to get at size dependent cation effects? I was thinking that the anion radius could be artificially set the cation radius, but that does not give any obvious solution when there is a mixture of Na and K. We really appreciate any help.

Here's one of our input files, if it helps (though the precise grid and radius parameters have been messed with a bit):

```
elec
    mg-auto
    cglen 24.8676 31.6608 41.0278 # coarse grid
    fglen 24.8676 31.6608 41.0278 # fine grid
    dime 33 33 33
    cgcent mol 1 # center the grids at the molecule
    fgcent mol 1 # center the grids at the molecule
    mol 1
    npbe # nonlinear
    bcfl mdh # Specifies the type of boundary conditions used to solve the Poisson-Boltzmann equation. mdh is better but expensive for large molecules
    pdie 4.0000  # pdie is the floating point value of the unitless biomolecular dielectric constant. This is usually a value between 2 to 20, where lower values consider only electronic polarization and higher values consider additional polarization due to intramolecular motion. The dielectric value must be ≥1
    sdie 78.5400 # diel is a floating point number representing the solvent dielectric constant (unitless). This number must be ≥1. Bulk water at biologically-relevant temperatures is usually modeled with a dielectric constant of 78-80.
    ion charge 1.000000 conc 1.000000 radius 1.815000
    ion charge -1.000000 conc 1.000000 radius 1.810000
    srfm smol # model used to construct the dielectric and ion-accessibility coefficients. smol seems ok
    chgm spl2 # biomolecular point charge interpolation, this means cubic spline
    sdens 20.00 # This keyword specifies the number of quadrature points per Å2
    srad 1.20 # radius of the solvent molecules; this parameter is used to define various solvent-related surfaces and volumes (see srfm (elec)). This value is usually set to 1.4 Å for a water-like molecular surface
    swin 0.30 # spline window width (in Å). Usually 0.3 Å.
    temp 310.15
    calcenergy total
    calcforce no
end
```

**Comment by sobolevnrm** [comment]
Hello -- this is the expected behavior:  APBS only uses the largest ion radius to set the ion-accessibility map.

Thank you.
