### ISSUE TITLE
!!! WARNING !!!  APBS NOT available !

### ISSUE THREAD

**Issue by zhangyunjiang1** [Electrostatics/apbs#201]
!!! WARNING !!!  APBS NOT available !

>> 0. set up environmets and parameters: OK !

>> 1. pre-processe trajectory: OK !

>> 2. generate qrv file: OK !

>> 3. run MM-PBSA calculatons
awk: line 593: function asorti never defined

I would like to ask about this problem. Calling APBA with gmx_mmpbsa will bring the above error message.

**Comment by sobolevnrm** [comment]
I am sorry but we are not the developers of the gmx_mmpbsa package and are not able to help you with this issue.  Have you tried contacting the GROMACS mailing lists?
