### ISSUE TITLE
Inconsistent results when switching the order of protein and ligand in PQR file

### ISSUE THREAD

**Issue by wquc** [Electrostatics/apbs#211]
Dear All,

I have a PQR file containing a protein with a ligand, and I'd like to caculate properties like electrostatic complementarity based on the output of APBS. 

When I switch the order of protein and ligand records in PQR file, i.e.

from
```
ATOM ... (blocks of protein)
ATOM ... (blocks of ligand)
```
to
```
ATOM ... (blocks of ligand)
ATOM ... (blocks of protein)
```

I noticed a minor difference in the output file:
```
# records of protein-first
-8.417152e-01 -8.433297e-01 -8.448692e-01
-8.463528e-01 -8.477795e-01 -8.491486e-01
-8.504332e-01 -8.516562e-01 -8.528182e-01
...
```

```
# records of ligand-first
-8.410779e-01 -8.426899e-01 -8.442271e-01
-8.457085e-01 -8.471332e-01 -8.485004e-01
-8.497832e-01 -8.510046e-01 -8.521651e-01
...
```

These differences seem to be negligible, however, it will affect subsequent calculations and cause some positve correlations to be negative. I've tested version 1.2.1, 1.4.1 and 3.3.0, and they all gave the same results.

So I was wondering is this normal? If so, how to choose the proper order?

Thank you for the time!

**Comment by sobolevnrm** [comment]
Hello --

The process for placing and optimizing hydrogens is not linear and therefore should be expected to differ if the atom order is altered.  However, as you pointed out, the difference should be small.  There is no preferred order for protein and ligand--although many users place the protein first.

Thank you,

Nathan
