### ISSUE TITLE
VASSERT: ASSERTION FAILURE!  filename /home/ubuntu/git/apbs-pdb2pqr/apbs/src/mg/vgrid.c

### ISSUE THREAD

**Issue by SehrishJamal** [Electrostatics/apbs#214]
I am using APBS 3.0.0 (pre-compiled) version as an extension to born profiler for plotting born profile against the pore axis however upon execution with documented parameters every time it shows ASSERTION error.   
-------------------------------------------------------------------------------------------------------------------
CALCULATION #6 (complex_S): MULTIGRID
  Setting up problem...
  Vpbe_ctor:  Using max ion radius (1.81 A) for exclusion function
  Debye length:  9.71135 A
  Current memory usage:  521.146 MB total, 1029.647 MB high water
  Using cubic spline charge discretization.
  Grid dimensions: 129 x 129 x 129
  Grid spacings: 0.391 x 0.391 x 0.391
  Grid lengths: 50.000 x 50.000 x 50.000
  Grid center: (69.288, 63.039, 60.171)
  Multigrid levels: 4
  Molecule ID: 3
  Linearized traditional PBE
  Boundary conditions from focusing
  2 ion species (0.100 M ionic strength):
    0.950 A-radius, 1.000 e-charge, 0.100 M concentration
    1.810 A-radius, -1.000 e-charge, 0.100 M concentration
  Solute dielectric: 10.000
  Solvent dielectric: 80.000
  Using "molecular" surface definition; no smoothing
  Solvent probe radius: 1.400 A
  Temperature:  298.150 K
  X-shifted dielectric map to be written to dielx_cpx_S.dx.gz
  Y-shifted dielectric map to be written to diely_cpx_S.dx.gz
  Z-shifted dielectric map to be written to dielz_cpx_S.dx.gz
  Kappa map to be written to kappa_cpx_S.dx.gz
  Charge distribution to be written to charge_cpx_S.dx.gz
  Skipping solve for mg-dummy run; zeroing solution array
  Calculating forces...
  Writing x-shifted dielectric map to dielx_cpx_S.dx.gz
  Writing y-shifted dielectric map to diely_cpx_S.dx.gz
  Writing z-shifted dielectric map to dielz_cpx_S.dx.gz
  Writing kappa map to kappa_cpx_S.dx.gz
  Writing charge distribution to charge_cpx_S.dx.gz
----------------------------------------
CLEANING UP AND SHUTTING DOWN...
Destroying force arrays.
No energy arrays to destroy.
Destroying multigrid structures.
Destroying finite element structures.
Destroying 3 molecules
Final memory usage:  0.001 MB total, 1029.647 MB high water

Thanks for using APBS!

Running draw_membrane2a ... [run_drawmembrane()]
----------------------------------------------------------------
* draw_membrane2a.c                                   04/26/11 *
----------------------------------------------------------------
draw_membrane2  -- (c) 2008 Michael Grabe [09/02/08]
draw_membrane4  -- (c) 2010 Michael Grabe [07/29/10]
draw_membrane2a -- (c) 2010,2011 Oliver Beckstein [04/26/11]
Published under the Open Source MIT License (see http://sourceforge.net/projects/apbsmem/).
Based on http://www.poissonboltzmann.org/apbs/examples/potentials-of-mean-force/the-polar-solvation-potential-of-mean-force-for-a-helix-in-a-dielectric-slab-membrane/draw_membrane2.c
----------------------------------------------------------------
Using hard-coded names with your infix to find files: infix=_prot_L
Reading gzip-compressed dx files.
Modelling headgroup region of thickness 0.0 with epsilon=20.0
Running with these arguments:
>>> draw_membrane2a -Z -s 80.0 -c 80.0 -m 2.0 -p 10.0 -i 20.0 -a 0.0 -V 0.000 -I 0.100 -z 0.000 -d 40.000 -r 0.0 -R 0.0 -X 69.144 -Y 61.668 _prot_L
ERROR: dielx_prot_L.dx.gz not found in current directory.
       See -h for usage.
ERROR: draw_membrane2a _prot_L failed.
-- APBS Born profile job running on tcc07
++ apbs job_0000.in > job_0000.out
Warning: The 'nlev' keyword is now deprecated!
Vgrid_value:  Error -- no data available!
VASSERT: ASSERTION FAILURE!  filename /home/ubuntu/git/apbs-pdb2pqr/apbs/src/mg/vgrid.c, line 193, (0)
./job_0000.bash: line 43:  8758 Aborted                 (core dumped) nice ${APBS} job_0000.in > job_0000.out

**Comment by sobolevnrm** [comment]
Hello -- 

Can you please clarify?  It appears that the error is with the `draw_membrane` code which is not part of the APBS software suite.  Can you confirm?

Thank you,

Nathan

**Comment by SehrishJamal** [comment]
Hi,

Thank you for your reply! Yes the standalone APBS suit working fine for me however when I execute it with born profiler which is another code I encountered this error as I can't access the gzip  files where the dielectric maps are written. Are these maps are usually accessible? may be I am something.

Thanks!

**Comment by sobolevnrm** [comment]
The APBS output above indicated that these maps had been written out, so this looks like a problem with the APBS_membrane code.
