### ISSUE TITLE
EasyBuild-compiled apbs seg faults on Centos 7.9

### ISSUE THREAD

**Issue by nmelotlunarc** [Electrostatics/apbs#240]
Hi,

I wrote an [easybuild 4.5.5](https://easybuild.io/) easyconfig file ([APBS-3.4.1-foss-2020b.eb](https://github.com/Electrostatics/apbs/files/9132058/APBS-3.4.1-foss-2020b.eb.txt)) for APBS. The compilation works with no problem. When trying to run the `apbs` binary file generated, I get a flat out `segmentation fault` with no other indication on what the issue can be.

Without Easybuild, I configure the APBS sources with
```
cmake -S . -B build -DBLAS_LIBRARIES="`pkg-config --libs openblas`" -DLAPACK_LIBRARIES="`pkg-config --libs openblas`"
```
(cmake 3.18.4) followed by `cd build; make` then I try running `./src/apbs` and I still get a segmentation fault and no other output.

I found on [some random page](https://doeidoei.wordpress.com/2009/12/03/segmentation-fault-when-using-pymol-and-apbs/) an article about a similar issue. I tried to build APBS with a dependency to `Tk` and `Tcl` 8.6.10, and tried to forcefully load them (using [LMOD](https://lmod.readthedocs.io/en/latest/)) before running APBS but that did not help either.

I built and run APBS using [easybuild 4.5.5](https://easybuild.io/) on CentOS 7.9. I joined a [detailed build log](https://github.com/Electrostatics/apbs/files/9132124/easybuild-APBS-3.4.1-20220718.144042.log) in case you can spot something I might have missed. What can I try next?

**Comment by jmourino** [comment]
I have the same problem with and without easybuild.
Have you solved the error?

**Comment by nmelotlunarc** [comment]
I did not try since this post. Hopefully someone has an idea. Beside using a debugger, I have no idea on how to identify the issue.

**Comment by jmourino** [comment]
The version 3.4.0 works for me.

**Comment by nmelotlunarc** [comment]
Worked for me too. I have to run cmake with the flag -DPYTHON_MAX_VERSION="`echo "import platform; print platform.python_version()" | python`" or the configuration step would fail.

**Comment by sobolevnrm** [comment]
It looks like this is working for others and EasyBuild is not something we formally support for this code.  Therefore, I am going to close this issue.  Thanks.
