### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by Shingzzz** [Electrostatics/apbs#241]
**Describe the bug**
Hello! I try to install apbs-v1.5 on linux by source code, but I cann\`t find the installation instructions of v1.5. So, I try to install apbs like this:

**To Reproduce**
```bash
wget sourcecode.tar.gz
tar -zvxf sourcecode.tar.gz
cd apbs-1.5.0

#then I copy Geometric Flow, FETk, PBAM/PBSAM to /apbs-1.5.0/externals geoflow_c, fetk, pb_s_am (I don`t know the usage of TABI-PB)
#next I add the following fields to /apbs-1.5.0/CMakeLists.txt, /apbs-1.5.0/externals/fetk/maloc/CMakeLists.txt, /apbs-1.5.0/externals/geoflow_c/CMakeLists.txt, /apbs-1.5.0/externals/pb_s_am/CMakeLists.txt
#set (CMAKE_C_COMPILER "/usr/local/bin/clang")
#set (CMAKE_CXX_COMPILER "/usr/local/bin/clang++")
#set(CMAKE_C_FLAGS "-march=armv8.2-a  -fsigned-char -ffp-contract=off")
#set(CMAKE_CXX_FLAGS "-march=armv8.2-a  -fsigned-char -ffp-contract=off")

#then I try to cmake, and it works
mkdir build
cd build
cmake ..

#when I make, it fails :(
make
```

**Screenshots**
![image](https://user-images.githubusercontent.com/43072501/180406976-f144bb14-d5d3-4787-bd37-13e022c411de.png)
It\`s a common error. But this error doesn\`t happen and I can also make install, when I use GNU.
Therefore, I was wondering if you could provide an installation instruction or some advice. 
Thanks！！！！！！！！！！

**Desktop (please complete the following information):**
 - OS: openEuler 20.03 (LTS)
 - cmake version: 3.12.1
 - compiler: HUAWEI BiSheng Compiler 2.1.0.B010 clang version 12.0.0

**Comment by sobolevnrm** [comment]
The latest version of APBS is [3.4.1](https://github.com/Electrostatics/apbs/releases/tag/v3.4.1).  Please try that instead.  Unfortunately, we do not have the bandwidth to troubleshoot compilation errors on old versions.

**Comment by Shingzzz** [comment]
Thank you anyway, there is a learning assignment that I must install apbs-v1.5 by sourcecode,I will go to find another way by myself.

**Comment by Shingzzz** [comment]
> The latest version of APBS is [3.4.1](https://github.com/Electrostatics/apbs/releases/tag/v3.4.1). Please try that instead. Unfortunately, we do not have the bandwidth to troubleshoot compilation errors on old versions.

Thank you anyway, there is a learning assignment that I must install apbs-v1.5 by sourcecode,I will go to find another way by myself.
