### ISSUE TITLE
error: ld returned 1 exit status

### ISSUE THREAD

**Issue by xiaopangjun666** [Electrostatics/apbs#248]
I installed libsuitesparse-dev and libopenblas-serial-dev,then installed python3.6,but error:
![image](https://user-images.githubusercontent.com/48478201/195049243-32fb8904-0cc4-465e-aabb-51f9c0a568dd.png)
could you help me?please @jlec

**Comment by jlec** [comment]
Sorry @xiaopangjun666 i am not maintaining any gentoo packages at this time.

**Comment by sobolevnrm** [comment]
It looks like you're missing the METIS package.  We used to be able to retrieve this automatically from the Karypis group website but it looks like they may have removed the software.

**Comment by xiaopangjun666** [comment]
How to solve this problem？
