### ISSUE TITLE
APBS image only white

### ISSUE THREAD

**Issue by cyril-schroeder-ox** [Electrostatics/apbs#255]
**Describe the bug**
Using the APBS web server.
The produced molecular image is perfectly white, as opposed to blue-white-red - which is unexpected for this particular molecule as it contains charged residues. (PDB: 2L3I) Potentially relevant: the peptide contains a disulphide-bridged loop.

**To Reproduce**
On webserver:
- Load molecule into PDB2PQR tool and run job
- Continue with APBS job.
- View molecule in 3Dmol web tool.

**Expected behavior**
Visualisation of molecule with different shades of blue, red, white.

**Screenshots**
Problematic example:
![oxt4_side1](https://user-images.githubusercontent.com/92921659/202235666-16f99eb8-6bbd-4ec7-85e9-ab09e5c25b68.png)
Successful example using different molecule (PDB: 2PCO):
![lat1_side1](https://user-images.githubusercontent.com/92921659/202235900-68df2d18-f347-437c-947b-f46cf113b5c6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome

**Comment by sobolevnrm** [comment]
Hello --

2L3I worked when I tried it:

![image](https://user-images.githubusercontent.com/1933272/202874826-dffe8504-519a-4c84-80d4-1d2dbe9c7680.png)

Please see the calculation results at <https://server.poissonboltzmann.org/jobstatus?jobtype=apbs&jobid=sruto929gi&date=2022-11-19>.

I have encountered situations previously when the 3Dmol visualization browser window fails to retrieve the potential data and load the potential/colors onto the surface.  This seems to sometimes happen when there are network issues or interruptions; however, the problem isn't reproducible enough to troubleshoot.

Thank you for your detailed reporting of this issue.
