### ISSUE TITLE
Error: 0xc000007b on win10 of apbs 3.4.1 (and maybe ^3.3.0)

### ISSUE THREAD

**Issue by supernovaZhangJiaXing** [Electrostatics/apbs#256]
**Discription:**
The apbs program does not display messages when running in command:
``` bash
open terminal (e.g. git bash) on windows
cd /path/to/apbs/bin
./apbs.exe
```

If directly double-click the apbs.exe program, the program displayes the error message 0xc000007b.

**Desktop:**
 - OS: Windows 10
 - Environment: cmd and git bash
 - Version 3.4.1

**Additional context**
By the way,  where is the json format instruction of apbs input? I can only find traditional formats on the apbs website.

**Comment by sobolevnrm** [comment]
Can you please try running the program in Powershell or a standard command prompt rather than Git Bash and let me know if you encounter the same error?

The JSON documentation exists, it just isn't very good.  [This section of the manual](https://apbs.readthedocs.io/en/latest/using/input/new/index.html) provides an overview of the keys and values expected in JSON- or YAML-format input.  Sorry we don't have more direct examples -- I'll create an issue to generate these in the future.

**Comment by supernovaZhangJiaXing** [comment]
Sure. I have tried to run apbs in Powershell and command prompt, and it also did not give any output. I have checked the task manager and did not see redundant process. My junior fellow apprentice tried to run `apbs.exe` in his command prompt on Windows 11, and also got the 0xc000007b error message. Seems that we both lack some basic libs that the pre-compiled apbs need.
Thank you for the documentation! I previously neglected the instructions of API and got confused. Now I think maybe I can try again to build an input-file generator for apbs. Furtherly, I wish that somday I may see the typical example(s) of apbs in the documentation. 
Thank you! 
;-)

**Comment by supernovaZhangJiaXing** [comment]
By the way, is it currently possible to pass json file to apbs as input file? I tried to write a sample but got "undefined keyword" error.

**Comment by sobolevnrm** [comment]
Let's just address one problem at a time in this issue.  I'll add your other question about JSON to #257 .

**Comment by sobolevnrm** [comment]
When I try to run APBS 3.4.1 from Powershell on Win 11, I receive no error--it simply doesn't work.  When I try to run it from the Command Prompt, I get the following pop-up window error:

![image](https://user-images.githubusercontent.com/1933272/204033720-9f9b9e20-55a2-404b-8380-8a478d0aa2ab.png)

**Comment by supernovaZhangJiaXing** [comment]
We all have python 3.9 on our computers.

**Comment by supernovaZhangJiaXing** [comment]
I asked an expert and got the solution: get a 32-bit [python39.dll](https://www.dll-files.com/python39.dll.html) and put it in the same directory with apbs.exe. I also tested the 64-bit python39.dll and it could not work. It seems that you missed this dll file after compiling apbs on windows.

**Comment by sbwiecko** [comment]
> When I try to run APBS 3.4.1 from Powershell on Win 11, I receive no error--it simply doesn't work. When I try to run it from the Command Prompt, I get the following pop-up window error:
> 
> ![image](https://user-images.githubusercontent.com/1933272/204033720-9f9b9e20-55a2-404b-8380-8a478d0aa2ab.png)

I have the same issue, so I went back to apbs-3.0.0, it works just fine without Python3.9.
