### ISSUE TITLE
Fix test coverage and integrate with Travis CI

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs#27]

**Comment by intendo** [comment]
For C/C++ code, we abandoned Travis CI in favor of Github Actions for Linux/Mac and Appveyor for Windows.

For the new Python code, Scons is gone and pytest has been implemented but not added to any CI.

Would you like me to add the flake8, black, and pytest apbs/test/ to the Github Actions and Appveyor?

**Comment by sobolevnrm** [comment]
If you don't mind, that would be great.  Thanks!

**Comment by intendo** [comment]
Closed by PR #161
