### ISSUE TITLE
Error: while loading shared libraries: libamd.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by huanggewudi** [Electrostatics/apbs#275]
when I run APBS, sometimes I get this error:

Error: while loading shared libraries: libamd.so.1: cannot open shared object file: No such file or directory

python3.7  apbs1.5

most time work successful.

**Comment by huanggewudi** [comment]
maybe because when I run pdb2pqr have this error sometimes(1/10 pdbs):
TypeError: '<' not supported between instances of 'PotentialBond' and 'PotentialBond'

**Comment by sobolevnrm** [comment]
I'm sorry but I don't understand your question -- or questions?  If there are two questions here, please post full descriptions using the provided templates in the APBS and PDB2PQR issue tracking interfaces.  Thank you.
