### ISSUE TITLE
fail to reproduce 

### ISSUE THREAD

**Issue by qqh2020** [Electrostatics/apbs#276]
Hi there,

I used the PDB2PQR/APBS web server on Chrome to calculate electrostatic potential for the nicotinic acetylcholine receptor (PDB: 5kxi). The result (middle panel) is different from published _**Figure d**_ (right panel), shown in the snapshot attached below. 

The whole process is done mostly by default, except ion parameters I have used (ion1: +1/0.15M/radius 2; ion2: -1/0.15M/radius 2).

I also generated the vaccum electrostatics distribution via Pymol (left panel), which is more or less similar to the published figure.

What parameters on web server should I use to reproduce the same result as **_Figure d_**? 

Thanks for your help.
qqh

![Screenshot 2023-07-01 at 16 57 26](https://github.com/Electrostatics/apbs/assets/138289866/d777bb0d-583c-47d2-890f-004c1ad76283)

**Comment by sobolevnrm** [comment]
I'm sorry but I have no idea what settings were used to produce the figure in the paper, nor do I have access to the paper.

**Comment by qqh2020** [comment]
Hi Nathan,thanks for your immediate response. I have figured out a workaround to reproduce the Figure published.I checked the charge of residues calculated in the pqr file,  which are correctly negative charged.  Likely, the inconsistency occured during visualization. I then used APBS_electrostatics implemented in Pymol instead of the APBS_plugin tool to show the surface potential, it's finally similar to the Figure. The inconvenience of this solution is that the charge range can only be shown symmetrically.Best,qqh发自我的手机-------- 原始邮件 --------发件人： Nathan Baker ***@***.***>日期： 2023年7月1日周六 晚上10:05收件人： Electrostatics/apbs ***@***.***>抄送： qqh2020 ***@***.***>, Author ***@***.***>主    题： Re: [Electrostatics/apbs] fail to reproduce  (Issue #276)
I'm sorry but I have no idea what settings were used to produce the figure in the paper, nor do I have access to the paper.

**Comment by sobolevnrm** [comment]
Wonderful!  I'm glad the problem is resolved.  Thank you for the update.
