### ISSUE TITLE
write statement produces incorrect filenames on linux

### ISSUE THREAD

**Issue by fvmarcoline** [Electrostatics/apbs#285]
Bug: Write statements on linux produce incorrect filenames. It appears that the numerical suffix is being written in a strange (hexidecimal?) floating point format, instead of as an integer.

Versions effected: apbs 1.2.1 through 3.4.1 on linux.

To reproduce: Run any test case which includes the following write statement:
  write dielx dx dielx_1
or any other numerically suffixed write statement.

Expected result: A file named dielx_1.dx
Actual result: A file named dielx_1-P0E.dx

Excerpt from stdout from apbs 3.4.1:

----------------------------------------
CALCULATION #1 (solv0): MULTIGRID
  Setting up problem...
  Vpbe_ctor:  Using max ion radius (2 A) for exclusion function
  Debye length:  9.71135 A
  Current memory usage:  1001.160 MB total, 1001.160 MB high water
  Using cubic spline charge discretization.
  Grid dimensions: 161 x 161 x 161
  Grid spacings: 1.875 x 1.875 x 1.875
  Grid lengths: 300.000 x 300.000 x 300.000
  Grid center: (0.000, 0.000, 0.000)
  Multigrid levels: 4
  Molecule ID: 1
  Linearized traditional PBE
  Zero boundary conditions
  2 ion species (0.100 M ionic strength):
    2.000 A-radius, 1.000 e-charge, 0.100 M concentration
    2.000 A-radius, -1.000 e-charge, 0.100 M concentration
  Solute dielectric: 10.000
  Solvent dielectric: 80.000
  Using "molecular" surface definition; no smoothing
  Solvent probe radius: 1.400 A
  Temperature:  298.150 K
  X-shifted dielectric map to be written to dielx_1.dx
  Y-shifted dielectric map to be written to diely_1.dx
  Z-shifted dielectric map to be written to dielz_1.dx
  Kappa map to be written to kappa_1.dx
  Charge distribution to be written to charge_1.dx
  Skipping solve for mg-dummy run; zeroing solution array
  Calculating forces...
  Writing x-shifted dielectric map to dielx_1-PE0.dx
  Writing y-shifted dielectric map to diely_1-PE0.dx
  Writing z-shifted dielectric map to dielz_1-PE0.dx
  Writing kappa map to kappa_1-PE0.dx
  Writing charge distribution to charge_1-PE0.dx
----------------------------------------

**Comment by sobolevnrm** [comment]
It appears your binary was compiled with multiprocessor support.  This is the desired behavior for multi-processor binaries:  the output files are labled with "PE#" where "PE" stands for "Processing Element" and "#" is the processor ID.
