### ISSUE TITLE
Modernize documentation on RTD

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs#41]
It would be great to move the relevant APBS documentation to Sphinx for support on RTD.  This probably has (at least) two parts:

* [x] @sobolevnrm can work on migrating the existing documentation from https://github.com/Electrostatics/apbs-pdb2pqr/tree/master/doc
* [ ] @intendo would you be willing to look at solutions like https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/ to support the C/C++ portion of the API documentation?

**Comment by intendo** [comment]
I tried to implement this but I think I am missing something because the example no longer works. I commented the sections in the files:
- docs/CMakeLists.txt
- docs/Doxyfile
- docs/conf.py.in
- docs/index.rst files

**Comment by sobolevnrm** [comment]
I unfortunately don't know enough about the project to help troubleshoot.  Maybe we just stick with the documentation as-is and focus on documenting the Python API for now?
