### ISSUE TITLE
Python Porting

### ISSUE THREAD

**Issue by ashermancinelli** [Electrostatics/apbs#47]
## Problem Description

Much of the current C/C++ code is difficult to maintain as expressed by other teammembers. Not many domain experts are proficient enough in this codebase to contribute as proficiently as they otherwise could (as I was informed by @intendo) were the codebase in Python.

## Describe the solution you'd like

I think we should take a multi-phasic approach to porting this code to Python, in order to work only in the smallest testable chunks.

### Step 1: Data Structures

Port the smallest data structures that are used frequently (as determined by @intendo's impressive callgraph work).

### Step 2: The Smallest Chunks

Port smaller routines/methods that operate on the smaller data structures

- Add as many tests as are reasonable to add after porting each method
- Grab a data-dump of the input/output of the C/C++ kernels to use as unit tests for the Python implementations to ensure that the refactor correctly replicates the old kernels
- heavily document the apparent responsibilities of all routines/data structures that are ported

### Step 3: Port More Complicated Routines

- Write unit tests for larger routines/methods in the same way that the smaller routines/methods were tested
- The smaller methods are already tested at this point, so we know that as long as we compose the methods in the same way, the larger tests will also perform the same way. These tests will likely not be as long as the methods themselves as a result.

### Step 4: Reevaluation

Re-evaluate the algorithms and data structures used. At this point, we would have tests for the highest-level routines that are used in the codebase. We could therefore test a new implementation in the same way, with more involvement from domain experts that could more meaningfully contribute to the project. We would therefore have full assurance that our refactor would be consistent with the old implementation.

We would also be able to swap out different python implementations for the larger kernels since we would have tests all the way down to the smallest chunks. We would know exactly where/when our new implementation differed from the old.

### Alternative 1 

We could attempt to port over larger chunks of the at once, however I don't think this is the best route.
For example, in the directory `apbs/src/routines.c` we have the function `solveMG`, which is the most frequently called function out of all the profiled runs @intendo ran. This calls `Vpmg_solve` in another file, which performs many steps before calling `Vmgdriv` or `Vnewdriv` depending on the options. In yet another file, `Vmgdriv` then performs many more operations before calling `Vmaxlev`, `Vmgsz`, and `Vmgdriv2`, each of which take a massive number of parameters and operate on many of the same massive data structures.

In my opinion and experience, porting `solveMG` will only really be possible once we have tests for the smaller routines (`Vmgdriv`, `Vmaxlev`, etc), all the way down to the bottom.

_NOTE: None of this is to disparage the original authors of this code - it was clearly written by talented engineers and domain experts. However, if we are to port (or interface) this to Python, I believe we will have to take this step by (well-tested) step._

### Alternative 2

We could also keep the python bindings to this program relatively thin, in which case I think we ought to just generate some Python bindings through the cpython API and let users work with the API directly. However, from my understanding, other members of this project strongly prefer not to take this route.

## Additional context

I have some small working examples of python implementations of `Vatom` and `Vlist`, along with unit tests to demonstrate. This is not the most thorough example, but nonetheless showcases how we might go about porting the program to python whilst keeping the organization of the code roughly the same until we have enough tests built up to really refactor substantial algorithms.

## Progress

The following have Python implementations that are thoroughly tested (102 tests in total):

- Chemistry
    - [x] Atom
    - [x] AtomList
    - [x] CellList
    - [ ] Atom Complex Calculations (`Vacc` class)
        - [ ] `atom_surface` needs tests
        - [ ] `accessable_outside_inflated_venderwalls_rad` needs tests
- Geometry
    - [x] Surface (partial)
    - [ ] Sphere
        - [ ] `spherical_distribution` needs testing

**Comment by ashermancinelli** [comment]
Note also that [the propka](https://github.com/jensengroup/propka) repo has an implementation of an Atom class (and other common utilities), though they are quite different from what we see in this repo. Perhaps when we have enough tests in place, we can use propka as a dependency and write implementations for the higher level algorithms in this repo using the classes in propka.

**Comment by ashermancinelli** [comment]
As per my conversation with @intendo offline, he and Arron Phillips will work on test cases which require a bit more domain knowledge, such as the method `accessable_outside_inflated_venderwalls_rad` of the class `AtomComplexCalc` (formerly method `ivdwAccExclus` of class `Vacc`).

**Comment by sobolevnrm** [comment]
> Note also that [the propka](https://github.com/jensengroup/propka) repo has an implementation of an Atom class (and other common utilities), though they are quite different from what we see in this repo. Perhaps when we have enough tests in place, we can use propka as a dependency and write implementations for the higher level algorithms in this repo using the classes in propka.

It would be *outstanding* if we could figure out how to expand the PROPKA Atom class to include the functionality we need in PDB2PQR.

**Comment by ashermancinelli** [comment]
It almost feels like we have the opposite situation with the PROPKA atom class - it seems to have an *immense* amount of data/behavior associated with it, and not much overlap with what we have here. But we can still investigate this 😄

**Comment by sobolevnrm** [comment]
The overall approach outlined here looks great to me.

**Comment by ashermancinelli** [comment]
Closing for now in favor of interfacing C code with python and gradually porting as needed. We can reopen when this is again relevent.
