### ISSUE TITLE
Issues Building APBS

### ISSUE THREAD

**Issue by itaneja2** [Electrostatics/apbs#61]
I'm on Mac OS 10.15.16 and am trying to build APBS from source (had no luck with the binary after trying for hours). I've followed the instructions on the website, but have not had any luck (specifically, if I clone the master branch I'm able to run cmake but then make crashes; if I try the specific release 3.0, cmake crashes). 

If possible, I would really appreciate if someone could add some more detailed step by step instructions regarding how to build APBS from source. This is a great piece of software, but some more documentation would go a long way.

**Comment by sobolevnrm** [comment]
Hi -- are you trying to build from the master branch (not recommended) or the 3.0.0 release (https://github.com/Electrostatics/apbs/releases/tag/v3.0.0)?  Thank you.

**Comment by itaneja2** [comment]
I tried the master branch and the 3.0.0 release, but had difficulties with both.

**Comment by intendo** [comment]
We updated the code on the master branch and the documentation today. 

https://apbs.readthedocs.io/en/latest/getting/source.html

Hopefully this helps you out.

**Comment by itaneja2** [comment]
Awesome. It works! Thank You :)
