### ISSUE TITLE
APBS 1.5 binary installed, doesn't run multiple tthreads!

### ISSUE THREAD

**Issue by ncclementi** [Electrostatics/apbs#7]
I recently download the binary from the 1.5 version and after fixing the LD_LIBRARY_PATH, I was able to run a case. However it doesn't run in multiple threads. 
The same input file, runs in multiple thread in a 1.4.1 version I had installed. I tried to install the 1.5 binary in different machines and I always get the same problem. It only runs in 1 thread. 

Any ideas on what can be causing this? 

For the record, I have 1 processor with 4 physical cores (hyperthreading 8) . The input file looks like:
```
read 
    mol pqr built_parse.pqr
end

# LYSOZYME SOLVATION ENERGY -- SOLVATED STATE
elec name lys-solv
    mg-manual
    dime 257 161 257  
    glen 50 40 50 
#    glen 69.43 61.38 77.82
    gcent mol 1
    mol 1
    lpbe
    bcfl mdh
    ion charge 1 conc 0.15 radius 2.0                
    ion charge -1 conc 0.15 radius 2.0      
    pdie 4.0
    sdie 80.00
    chgm spl2
    srfm mol
    srad 1.4
    swin 0.3
	sdens 50.0
    temp 300.00
    calcenergy total
    calcforce no            
end

# LYSOZYME SOLVATION ENERGY -- REFERENCE STATE
elec name lys-ref
    mg-manual
    dime 257 161 257 
    glen 50 40 50 
#    glen 69.43 61.38 77.82
    gcent mol 1
    mol 1
    lpbe
    bcfl mdh
    ion charge 1 conc 0.00 radius 2.0                
    ion charge -1 conc 0.00 radius 2.0 
    pdie 4.0
    sdie 4.00
    chgm spl2
    srfm mol
    srad 1.4
    swin 0.3      
	sdens 50.0
    temp 300.00
    calcenergy total
    calcforce no
end

# Lysozyme solvation energy
print elecEnergy lys-solv - lys-ref end

quit
```

**Comment by intendo** [comment]
By default, the ENABLE_OPENMP is turned on in CMake so the resulting binaries will be multithreaded.

**Comment by namus** [comment]
> By default, the ENABLE_OPENMP is turned on in CMake so the resulting binaries will be multithreaded.

For some reason, it is not the case for me. After running cmake, in the CMakeCache.txt file I found:
ENABLE_OPENMP:BOOL=OFF

I had to turn it ON to enable OpenMP. Also, the current binary downloaded from github doesn't run on multiple threads as mentioned in the original issue. So I guess the issue still persists, but can be resolved by compilation from source code after enabling OpenMP manually as mentioned above.

**Comment by intendo** [comment]
This may have been a result of the complicated CMake build system with all the external dependencies. We have revamped the CMake build system to use pre-built versions of all the external dependencies with greatly reduces the complexity (and time) to build APBS.
