### ISSUE TITLE
Possible iterator bug (i instead of ii)

### ISSUE THREAD

**Issue by dakami** [Electrostatics/apbs#71]
https://github.com/Electrostatics/apbs/blob/master/src/pmgc/buildGd.c#L232

            for(ii=2; ii<=*nx-1; i++) {
               i = 2 * ii - 1;

This appears to be an infinite loop, never reached (at least in my test cases) because VbuildG_1 isn't being called.  Technically this would still break if nx was variable, but it doesn't seem to be, and none of the other loops do this.  I only noticed because it's a noncanonical for loop and OpenMP errors out on them.

**Comment by sobolevnrm** [comment]
That's a great catch!  I agree that it looks like a bug; the Galerkin construction of the operator should be looping over interior grid points (`ii`) and it appears that `i` is being incremented from an uninitialized value. 

@ashermancinelli or @intendo do you have time to test this?  The fact that we haven't encountered this problem before makes me think it's in an unused part of the code -- so this might be helpful for your refactoring activities.

Thanks, @dakami !

**Comment by ashermancinelli** [comment]
Great catch @dakami. If it's unused, I foresee troubles testing it. Do we have a use case in which we know this function is called?

**Comment by sobolevnrm** [comment]
I'm 99% sure it's a bug... If it's unused, I think we should delete it as part of the refactoring process.  We can add it back later if needed.

**Comment by dakami** [comment]
I'd assume mg_manual, and the python bindings, would want it to be there?  Refactoring possibly should make sure it's not ultimately a faster way to do things before removing it.

**Comment by intendo** [comment]
That line should probably be changed to `for(ii=2; ii<=*nx-1; ii++)` to be consistent with the outer 2 loops for jj and kk.

**Comment by ashermancinelli** [comment]
This issue is resolved in merged #84
