### ISSUE TITLE
Build with precompiled external dependencies

### ISSUE THREAD

**Issue by ashermancinelli** [Electrostatics/apbs#81]
None of our external dependencies are under development (except pybind11), and a major prohibitor for our CI pipeline is the build time. I propose we upload tarballs of prebuilt dependencies so we can run CI on all our branches and reduce build time.

CC @intendo @sobolevnrm

**Comment by intendo** [comment]
@ashermancinelli you will need a prebuilt tarball for each external for each platform (Linux, MacOS, Windows 10).

**Comment by ashermancinelli** [comment]
Do you have access to a windows machine? I can build on amd64 linux & mac.

**Comment by sobolevnrm** [comment]
Yes; if you tell me what to do, I can test.

**Comment by ashermancinelli** [comment]
@sobolevnrm Thanks! I will have an example ready for you once I figure out all the second-generation dependencies. I have a build script [here](https://github.com/ashermancinelli/apbs-deps) which I hope to pull into the electrostatics project once it's working. This will serve as the base for building everything on windows.

Are either of you aware of which dependencies need each other? For example, `geoflow_c` and `pb_solvers` both seem to depend on APBS, not vice versa as I expected. I think sorting this out would mean alleviating many of our dependency and build-time woes.

CC @intendo

**Comment by intendo** [comment]
@ashermancinelli I think that `FETK` is a standalone package that we use for the machine dependent abstraction (`MALOC`) and we can also use the Finite Element solver.

I think the `geoflow_c` and `pb_solvers` use the APBS data structures to implement their solvers and/or other parts of their libraries.

CC @sobolevnrm

**Comment by ashermancinelli** [comment]
@sobolevnrm Do you know if `geoflow_c` and `pb_solvers` strictly depend on APBS? Or does APBS in any way also depend on those two?

**Comment by ashermancinelli** [comment]
To really fix this issue, I think we need to decouple geoflow_c, pb_solvers, and APBS. APBS should only build/run self-contained tests, and tests that rely on geoflow_c or pb_solvers should run in their respective repos.

**Comment by sobolevnrm** [comment]
> @ashermancinelli I think that `FETK` is a standalone package that we use for the machine dependent abstraction (`MALOC`) and we can also use the Finite Element solver.
> 
> I think the `geoflow_c` and `pb_solvers` use the APBS data structures to implement their solvers and/or other parts of their libraries.
> 
> CC @sobolevnrm

FEtk provides both finite element support and the MALOC hardware abstraction library.

**Comment by sobolevnrm** [comment]
> @sobolevnrm Do you know if `geoflow_c` and `pb_solvers` strictly depend on APBS? Or does APBS in any way also depend on those two?

Yes, I believe those libraries are intertwined with APBS -- but am not sure.

**Comment by sobolevnrm** [comment]
> To really fix this issue, I think we need to decouple geoflow_c, pb_solvers, and APBS. APBS should only build/run self-contained tests, and tests that rely on geoflow_c or pb_solvers should run in their respective repos.

APBS relies on these two libraries so I think we at least need integration tests?

**Comment by sobolevnrm** [comment]
> @sobolevnrm Thanks! I will have an example ready for you once I figure out all the second-generation dependencies. I have a build script [here](https://github.com/ashermancinelli/apbs-deps) which I hope to pull into the electrostatics project once it's working. This will serve as the base for building everything on windows, and should build and package everything needed for APBS.
> 
> Are either of you aware of which dependencies need each other? For example, `geoflow_c` and `pb_solvers` both seem to depend on APBS, not vice versa as I expected. I think sorting this out would mean alleviating many of our dependency and build-time woes.
> 
> CC @intendo

We have a lot of potential actions/issues in this thread.  Can we fork some of them off by referencing in new, more specific, issues?  Thanks.

**Comment by ashermancinelli** [comment]
As far as APBS is concerned, I am addressing this in [my own repo](https://github.com/ashermancinelli/apbs-deps) which we can pull into the Electrostatics project when it's ready. It already compiles eigen, pybind, and fetk into a release tarball available in the repo. We should already be able to integrate this into our APBS CI to cut pipeline times down by a huge margin. We should probably enable CI for all branches once this is set up.

**Comment by ashermancinelli** [comment]
@intendo @sobolevnrm I would appreciate you two looking at branch `pip-dev`. I think this may be a more portable solution and closer to what we ultimately want to have.

```bash
$ python setup.py sdist
...
$ cp dist/APBS-3.0.0.tar.gz /tmp
$ cd /tmp
$ tar xvzf APBS-3.0.0.tar.gz
$ cd APBS-3.0.0
$ python -m venv env
$ . env/bin/activate
$ python setup.py build
```
This will tar up the repo and all dependencies. From the tarball, we can use the setup.py script to build and install the python shared libs to the right place, as well as all the C libs.

**Comment by ashermancinelli** [comment]
Specifically for @intendo : we could tar the repo *after* a `python setup.py build` as the first stage in a CI pipeline and run all tests in another pipeline. We could only trigger the first pipeline if something changes in the C code, and this should drastically reduce CI time used like we hoped yet we could stay relatively platform independent.

**Comment by intendo** [comment]
I added the upgrade pip command to your commands. It builds on my Mac but the `apbs` binary is still dynamically linked to the compiler:

```
ldd env/bin/apbs 
env/bin/apbs:
        /usr/local/opt/gcc@9/lib/gcc/9/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.28.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
        /usr/local/lib/gcc/9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

My guess is that those dynamic links come in from the apbs_pybind.cpython-38-darwin.so shared library:
```
ldd env/lib/apbs_pybind.cpython-38-darwin.so 
apbs_pybind.cpython-38-darwin.so:
        /usr/local/opt/gcc@9/lib/gcc/9/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.28.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
        /usr/local/lib/gcc/9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0) 
```

Can we get them to link to the static libstdc++.a and libgcc_s?
Or will the user building from source get their compiler's stdc++ libraries linked to the `apbs` binary and pybind library?

**Comment by ashermancinelli** [comment]
The user building from source should take care of that. We wouldn't distribute prebuilt binaries should we go with this option, but would still simplify user experience and reduce build times in CI.

**Comment by sobolevnrm** [comment]
Did you see this warning message?

```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
```

**Comment by sobolevnrm** [comment]
> The user building from source should take care of that. We wouldn't distribute prebuilt binaries should we go with this option, but would still simplify user experience and reduce build times in CI.

We will always need to provide prebuilt binaries for some users.

**Comment by sobolevnrm** [comment]
I *really* like this method of installation.  What's keeping us from merging this into master?  I tried to build the master branch on my Mac last night and couldn't get it to work.

**Comment by sobolevnrm** [comment]
Although the installation failed on my Mac in this branch too (spoke too soon):

```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.18/Modules/FindSWIG.cmake:105 (find_package_handle_standard_args)
  tools/python/CMakeLists.txt:6 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0/build/temp.macosx-10.9-x86_64-3.8/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    setup(
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0/env/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/bake113/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/bake113/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/bake113/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/bake113/opt/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/bake113/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/bake113/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0/tools/install_scripts/cmake_setuptools.py", line 35, in run
    self.build_extension(ext)
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0/tools/install_scripts/cmake_setuptools.py", line 77, in build_extension
    subprocess.check_call(
  File "/Users/bake113/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3/0/', '-DPYTHON_EXECUTABLE=/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0/env/bin/python', '-DENABLE_PYTHON=ON', '-DCMAKE_BUILD_TYPE=Release', '-DPYTHON_SITE_PACKAGES_DIR=lib/python3.8/site-packages', '-Dpybind11_DIR=/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0/env/lib/python3.8/site-packages/pybind11/share/cmake/pybind11', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/Users/bake113/OneDrive - PNNL/Documents/Git/tmp/APBS-3.0.0/env']' returned non-zero exit status 1.
```

Is there a way to include SWIG in the install process?

**Comment by intendo** [comment]
It worked on my Mac because I had SWIG installed. I think @ashermancinelli could help me figure out a way to remove SWIG with a hard-coded version of what SWIG produces or replace it with pybind11. I would have to defer to @ashermancinelli for which approaches we could try.

**Comment by ashermancinelli** [comment]
I would much rather port to pybind, but this is outside the scope of this issue and potentially very involved. Can we just list swig as a dependency and put the onus on the user to install it?

**Comment by ashermancinelli** [comment]
@sobolevnrm I'd personally like to see this working in all our CI before we merge. I think there's some more work needed to get this working on windows.

**Comment by ashermancinelli** [comment]
@intendo `python setup.py test` is a command class as well. We could pull in all our platform-specific testing utilities into this command so we have a platform-independent way to build, install, and test our repo.

**Comment by ashermancinelli** [comment]
@intendo Could you take a look at current `pip-dev` branch? Building `src/generic/nosh.c` is failing on windows, but I haven't touched anything under the src directory, so I may just be ignorant about building on windows.

**Comment by intendo** [comment]
@ashermancinelli what toolchain are you using on Windows?

**Comment by ashermancinelli** [comment]
choco, msvc 2015 I believe.

**Comment by intendo** [comment]
Look at the "Windows VM on Azure to build APBS" in the OneNote I sent you.

**Comment by ashermancinelli** [comment]
@intendo @sobolevnrm I have a precompiled apbs stored as a pip wheel which we should be able to upload to pip.

For example on linux:
```shell
$ pip install numpy pyparsing pytest
$ pip install apbs-3.0.0-cp38-cp38-linux_x86_64.whl
```
gets you:

```python
>>> import apbs
>>> apbs.bindings.swig.<any swig binding>
>>> apbs.bindings.pybind.<any pybind binding>
>>> apbs.bin.get_path() # This prints the path to the installation of the prebuilt binaries
>>> apbs.lib.get_path() # This prints the path to the installation of the prebuilt libraries
>>> import os
>>> os.listdir(apbs.lib.get_path())
['libapbs_routines.a', 'libapbs_pmgc.a', 'libapbs_mg.a', 'libapbs_generic.a', '__init__.py', '__pycache__']
>>> os.listdir(apbs.bin.get_path())
['value', 'uhbd_asc2bin', 'tensor2dx', 'smooth', 'similarity', 'multivalue', 'mgmesh', 'mergedx2', 'mergedx', 'dxmath', 'dx2uhbd', 'dx2mol', 'del2dx', 'coulomb', 'born', 'benchmark', 'apbs', 'analysis', '__init__.py', '__pycache__']
```

I've got the static libraries for gcc stdc and stdc++, so I'll try building with them and uploading as a release for current users. This should hopefully address #95 as well.

If we base all our tests based off of these installation paths, we should be able to write more resilient tests that better replicate the user's experience. This is currently in branch `pip-bdist-dev`, but I hope to merge into `pip-dev` soon. I'll try to test on windows and get packages out for linux and mac as soon as I can.

**Comment by ashermancinelli** [comment]
FYI I have the image I used to build the manylinux pip packages uploaded to [docker hub here](https://hub.docker.com/repository/docker/ashermancinelli/apbs_manylinux1_base).

**Comment by intendo** [comment]
@sobolevnrm I think we should be able to remove the tools/windows directory. It looks like it was used to create an apbs.exe on windows in the past.

**Comment by ashermancinelli** [comment]
@intendo @sobolevnrm If either of you can let me know what external libs must be built into apbs for release, I can build and test and deploy to pypi-testing and finally deploy to pypi with Nathan's account.

**Comment by sobolevnrm** [comment]
This is really cool!  Can you please update the documentation so I can
figure out how to use it?  That will help me understand what test cases
work/don't work, etc.

**Comment by ashermancinelli** [comment]
Thanks! I've updated readme in branch `pip-dev`, please let me know if there's anything you'd like me to clean up.

**Comment by sobolevnrm** [comment]
> @sobolevnrm I think we should be able to remove the tools/windows directory. It looks like it was used to create an apbs.exe on windows in the past.

@intendo -- I agree.

**Comment by sobolevnrm** [comment]
> @intendo @sobolevnrm If either of you can let me know what external libs must be built into apbs for release, I can build and test and deploy to pypi-testing and finally deploy to pypi with Nathan's account.

Ideally, all of them.

**Comment by sobolevnrm** [comment]
> @intendo @sobolevnrm I have a precompiled apbs stored as a pip wheel which we can upload to pip. I've already uploaded linux and macos builds which you can test with `pip install -i https://test.pypi.org/simple/ apbs`.
> 
> For example on linux:
> 
> ```shell
> $ pip install numpy pyparsing pytest
> $ pip install apbs-3.0.0-cp38-cp38-linux_x86_64.whl
> ```
> 
> gets you:
> 
> ```python
> >>> import apbs
> >>> apbs.bindings.swig.<any swig binding>
> >>> apbs.bindings.pybind.<any pybind binding>
> >>> apbs.bin.get_path() # This prints the path to the installation of the prebuilt binaries
> >>> apbs.lib.get_path() # This prints the path to the installation of the prebuilt libraries
> >>> import os
> >>> os.listdir(apbs.lib.get_path())
> ['libapbs_routines.a', 'libapbs_pmgc.a', 'libapbs_mg.a', 'libapbs_generic.a', '__init__.py', '__pycache__']
> >>> os.listdir(apbs.bin.get_path())
> ['value', 'uhbd_asc2bin', 'tensor2dx', 'smooth', 'similarity', 'multivalue', 'mgmesh', 'mergedx2', 'mergedx', 'dxmath', 'dx2uhbd', 'dx2mol', 'del2dx', 'coulomb', 'born', 'benchmark', 'apbs', 'analysis', '__init__.py', '__pycache__']
> ```
> 
> I've got the static libraries for gcc stdc and stdc++, so I'll try building with them and uploading as a release for current users. This should hopefully address #95 as well.
> 
> If we base all our tests based off of these installation paths, we should be able to write more resilient tests that better replicate the user's experience. This is currently in branch `pip-bdist-dev`, but I hope to merge into `pip-dev` soon. I'll try to test on windows as soon as I can.

This doesn't work for me.  The `pip install` goes OK but after it's installed, I get errors like:

```
(apbs-test) WE38570:apbs bake113$ python -m apbs apbs
Traceback (most recent call last):
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/apbs/apbs/__init__.py", line 1, in <module>
    from . import (
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/apbs/apbs/bindings/__init__.py", line 6, in <module>
    from . import pybind, swig
  File "/Users/bake113/OneDrive - PNNL/Documents/Git/apbs/apbs/bindings/pybind.py", line 1, in <module>
    from apbs_pybind import *
ModuleNotFoundError: No module named 'apbs_pybind'
```

**Comment by ashermancinelli** [comment]
Interesting. What OS version and python version are you running, and what's in the dir `/Users/bake113/OneDrive - PNNL/Documents/Git/apbs/apbs/bindings`?

**Comment by sobolevnrm** [comment]
Here's a different version of the error.  Running
```
conda create -n apbs-test numpy pyparsing pytest pip
conda activate apbs-test
pip install -i https://test.pypi.org/simple/ apbs
python -m apbs apbs
```
results in the error
```
Traceback (most recent call last):
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/site-packages/apbs/__init__.py", line 1, in <module>
    from . import (
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/site-packages/apbs/bindings/__init__.py", line 6, in <module>
    from . import pybind, swig
  File "/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/site-packages/apbs/bindings/pybind.py", line 1, in <module>
    from apbs_pybind import *
ImportError: dlopen(/Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/site-packages/apbs/bindings/apbs_pybind.cpython-38-darwin.so, 2): Library not loaded: @rpath/Python3.framework/Versions/3.8/Python3
  Referenced from: /Users/bake113/opt/anaconda3/envs/apbs-test/lib/python3.8/site-packages/apbs/bindings/apbs_pybind.cpython-38-darwin.so
  Reason: image not found
```

**Comment by sobolevnrm** [comment]
The other information you requested:

```
(apbs-test) WE38570:~ bake113$ uname -a
Darwin WE38570 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

and 

```
python --version
Python 3.8.5
```

**Comment by ashermancinelli** [comment]
Ah I linked by rpath to libpython. I thought I fixed that already but it must have just been for linux and windows. I'll rebuild and upload again.

**Comment by ashermancinelli** [comment]
I've uploaded a cleaned up wheel with no extra libs, so you shouldn't run into that error anymore. Could you reinstall from pip and try again? Also, please use the --verbose option and verify the wheel `apbs-3.0.0-4-cp38-cp38-macosx_10_15_x86_64.whl` is what you're getting.

**Comment by intendo** [comment]
@ashermancinelli I think part of the problem for me is that I am running the Lab approved Mojave (10.4.6) version of MacOSX. I am running Python 3.8.3. 
```
pip install -i https://test.pypi.org/simple apbs
Looking in indexes: https://test.pypi.org/simple
ERROR: Could not find a version that satisfies the requirement apbs (from versions: none)
```

How do I create a wheel version to put out on pypi?
ERROR: No matching distribution found for apbs

**Comment by ashermancinelli** [comment]
Yes, we have to build wheels for every platform and I haven't built for yours. You'll have to build with `python setup.py build` and `python setup.py bdist_wheel` before uploading to pypi with twine, but we can save pypi for later when we're ready for release. Is there a reason you want to upload your apbs build to pypi before it's ready?

**Comment by intendo** [comment]
We went a different route and precompiled the external dependencies. We may want to revisit this problem in the future as we move APBS to Python.
