### ISSUE TITLE
Decouple APBS from dependees

### ISSUE THREAD

**Issue by ashermancinelli** [Electrostatics/apbs#85]
**Is your feature request related to a problem? Please describe.**
The current build script builds all APBS's dependencies, as well as TABIPB, geoflow_c, and pb_solvers, which seem to actually be dependees of APBS and not really dependencies. I think all the APBS tests which rely on these repos should reside in their respective CI pipelines, and perhaps we can have another repo that uses all of them as submodules to run integration tests.

Our current CI pipelines take forever to run because they have to compile *everything*, but if we can decouple these prejects we can probably afford much better ci and make packaging the project much easier.

@intendo @sobolevnrm Do you know how dependent APBS is on TABIPB, geoflow_c, and pb_solvers, and which tests can be moved to those repos or perhaps a master repo for integration tests only?

FYI discussion began in #81

**Comment by nsoblath** [comment]
This is much improved in v3.4.0, though probably still not perfect.  I'm going to close this issue for now, and if there are still major problems, a new issue can be raised.
