### ISSUE TITLE
What are the units for floats in DX/DXBIN files?

### ISSUE THREAD

**Issue by dakami** [Electrostatics/apbs#88]
I was asked to provide the absolute strengths of electrostatic fields calculated by apbs.

As it happens, they are described as:

```
u(*,*,*)
The data values, ordered with the z-index increasing most quickly, followed by the y-index, and then the x-index.
```

They're doubles, but of what?

**Comment by sobolevnrm** [comment]
The [write](https://apbs.readthedocs.io/en/latest/using/input/elec/write.html?highlight=write) command writes out the electrostatic potential (not the field) in units of `kT/e`, where `k` is Boltzmann's constant, `T` is the temperature (in Kelvin), and `e` is the electron charge.  This is about 25.85 mV at 300 K.

**Comment by dakami** [comment]
Thank you!
