### ISSUE TITLE
Create PQRPARSER in Python

### ISSUE THREAD

**Issue by intendo** [Electrostatics/apbs#91]
Add pqrparser to existing python code.

Must:
- Read ATOMs from PQR file
- Generate a list of ATOMS
- Utilize eBNF grammar

**Comment by sobolevnrm** [comment]
Like https://github.com/Electrostatics/pdb2pqr/blob/968e15a2aac64cf9712abf7f8621793b75ea8b4d/pdb2pqr/io.py#L540 ?

**Comment by intendo** [comment]
Yes, but replacing 600+ lines of code with about 50.

**Comment by intendo** [comment]
Need to find only Keywords for ATOM and HETOM.

**Comment by intendo** [comment]
This was fixed in issue #119 and pull request #120
