### ISSUE TITLE
Reading dx files written by apbs is not working on windows in apbs versions 1.5 and 3.0

### ISSUE THREAD

**Issue by fvmarcoline** [Electrostatics/apbs#95]
**Describe the bug**
The APBS 1.5 and 3.0 windows versions downloaded from sourceforge, and the 3.0 windows version downloaded from https://github.com/Electrostatics/apbs/releases, can not read dx files which it creates.

**To Reproduce**
1) Rename the attached file A.pqr.txt to A.pqr
2) run:  apbs write.txt
3) run:  apbs read.txt

**Standard error from step 3:**
Vgrid_readDX:  Format problem with input file <dielx.dx>
Fatal error while reading from dielx.dx
Error reading dielectric maps!

Note that if you copy the output dx files from step 2 to macos, step three 3 runs correctly using APBS 1.5 and 3.0 from sourceforge.

[A.pqr.txt](https://github.com/Electrostatics/apbs/files/5316106/A.pqr.txt)
[read.txt](https://github.com/Electrostatics/apbs/files/5316107/read.txt)
[write.txt](https://github.com/Electrostatics/apbs/files/5316108/write.txt)

**Comment by sobolevnrm** [comment]
I cannot reproduce this issue with the master branch.  @intendo and @ashermancinelli -- how far off are we from another release?

**Comment by fvmarcoline** [comment]
I was also not able to reproduce this on master two days ago. I built apbs from master using cygwin/gcc on windows. I was able to run our normal test cases, but the results were way off of the expected results (the three test cases from Callenberg et al., 2010, PLoS ONE 5(9): e12722). Our (https://sourceforge.net/projects/apbsmem) build system runs these three test cases, at low resolution (> ant test) and at the published resolution (> ant full), and reports discrepancies with the published results. But I can't speak to the origin of these differences at the moment. If further investigation suggests these differences are real, I'll start a new thread.

I have not tried building using Microsoft's compiler yet.

But with the downloaded binaries, tested on two different windows 10 machines, apbs failed the above test with the above error.

**Comment by sobolevnrm** [comment]
I think we need to release some new binaries.  @intendo and @ashermancinelli -- is this feasible?

**Comment by intendo** [comment]
@sobolevnrm I think we can on Linux for sure. I am pretty sure we can on Windows (a bit more manually). I cannot for the life of me figure out how to make a binary on MacOSX with the user needing the compiler runtime libraries (we may just have to update the documentation and choose HomeBrew as the default?).

**Comment by ashermancinelli** [comment]
@sobolevnrm @intendo I have uploaded prebuilt binaries for mac, linux, and *windows* to the testing mirror of pypi. Can you both test these out for me? Installing them with this command: `pip install -i https://test.pypi.org/simple/ apbs` works for me.

**Comment by sobolevnrm** [comment]
Yes, but can you please update the documentation to describe what to do
after the pip install?  Thanks!

**Comment by fvmarcoline** [comment]
Hi everyone. Thank you for looking into this. The updated 3.0 on test.pypi.org, running on Windows 10 Home, does not fix the problem.

The .dx files seem to be correct. There are some slight formatting changes in the .dx files between apbs versions and OS versions, but those do not appear to be the problem.

Please let me know if there is any more information I can provide. Here is the result of running the above test case:

>"C:\Program Files\Python38\Lib\site-packages\apbs\bin\apbs.exe" read.txt

----------------------------------------------------------------------
    APBS -- Adaptive Poisson-Boltzmann Solver
    Version 3.0
[snip]
This executable compiled on Oct 22 2020 at 15:44:46

Parsing input file read.txt...
rank 0 size 1...
Parsed input file.
Got paths for 1 molecules
Reading PQR-format atom data from A.pqr.
  1 atoms
  Centered at (0.000e+00, 0.000e+00, 0.000e+00)
  Net charge 1.00e+00 e
Got paths for 1 dielectric map sets
Reading x-shifted dielectric map data from dielx.dx:
Vgrid_readDX:  Format problem with input file <dielx.dx>
Fatal error while reading from dielx.dx
Error reading dielectric maps!

**Comment by ashermancinelli** [comment]
Are you certain that files `dielx.dx diely.dx dielz.dx` are all written to your current working directory? I could not reproduce this on master. Seems to run just fine for me.

**Comment by fvmarcoline** [comment]
Yes. They are all present. You get a different error if they are not present:
```
Got paths for 1 dielectric map sets
Reading x-shifted dielectric map data from dielx.dx:
Vio_ctor2: some error occurred.
Vio_ctor: Vio_ctor2() failed.
Vgrid_readDX: Problem opening virtual socket dielx.dx
Fatal error while reading from dielx.dx
Error reading dielectric maps!
```

The error must be happening while parsing the file header, because the error occurs before the usual output: "Vgrid_readDX:  Grid dimensions %d x %d x %d grid\n".

When I build it for myself, it works fine, so it's hard for me to locate the problem. If you want to instrument a test version, I'd be happy to try it.

**Comment by ashermancinelli** [comment]
Thank you for your patience. I believe I have a fix which is working on all three platforms. The parser was not using the correct formatting specifier which caused a `size_t` and a `long unsigned int` comparison to fail on line 751 in `src/mg/vgrid.c` on windows. I'll push the change to branch `dx-parser-hotfix`, please try building the branch and see if it works for you.

**Comment by fvmarcoline** [comment]
If you could provide a binary, I would be happy to test it. I can not build the windows VS project (due to a strong desire to not create a Microsoft account).

**Comment by ashermancinelli** [comment]
I've uploaded the new binaries to pypi testing mirror, so if you `pip install -i https://test.pypi.org/simple/ apbs` it should work on your inputs. I just tested with your inputs and it worked for me.

**Comment by fvmarcoline** [comment]
That did the trick. Reading dx files works, and the results of our test cases are consistent with previous versions. Thank you for solving this. Reading dx files is a crucial feature for us and our users.
