### ISSUE TITLE
 Unable to allocate enough memory for problem size; dime 161 225 161

### ISSUE THREAD

**Issue by zhangw99775** [Electrostatics/apbs#97]
Hi,

When I use APBS to run one of my xx.in file, an error occurred sometimes. The error message 
is below, 

"Unable to allocate memory!
(This often means you don't have enough memory available for this calculation.)
FATAL ERROR: Unable to allocate enough memory for problem size.
FATAL ERROR: You requested 521613320 bytes of RAM.
FATAL ERROR: Check that your system has that much memory.
VASSERT: ASSERTION FAILURE!  filename ..\..\..\..\..\contrib\maloc\src\vsys\vmem.c, line 252, (ram != ((void *)0))"

My first question is, how to solve the low memory problem?

Besides that, I've tried to figure it out. I open the xx.in file and change the line "dime 161 225 161" to "dime 159 225 159". 
APBS run successfully. My second question is, what's the meaning of the three numbers and is it OK to enable the runing of the program through changing these numbers?

**Comment by sobolevnrm** [comment]
Can you please tell us more?

- What operating system are you using?
- How much memory do you have on your computer?
- What version of APBS were you using?

**Comment by zhangw99775** [comment]
I used windows10.
I have 13.9GB memory on my computer.
I used APBS 1.4

**Comment by sobolevnrm** [comment]
Can you please try APBS 3.0 instead?

Thank you.
